### ISSUE TITLE
Trying to set securityDefinitions

### ISSUE THREAD

**Issue by modstore** [nelmio/NelmioApiDocBundle#1023]
I'm trying to set securityDefinitions through config.yml but it's not being output. Not sure if I'm doing it wrong, but I can't find an example of how to do it.

```yml
    documentation:
        info:
            title: My Site
            version: 1.0.0
        securityDefinitions:
            api_key:
                type: apiKey
                name: api_key
                in: header
```
