### ISSUE TITLE
How do you configure authentication?

### ISSUE THREAD

**Issue by wraycode** [nelmio/NelmioApiDocBundle#1029]
I want to use api key or jwt in later,  but for now I just want /api/doc to use

      @Security("is_granted('IS_AUTHENTICATED_FULLY')")
I tried to run
./bin/console debug:config NelmioApiDocBundle

But all it lists is the basic config, where are the rest of the options?

**Comment by GuilhemN** [comment]
You can do that under `nelmio_api_doc: documentation:`, an example:
```yml
nelmio_api_doc:
    documentation:
        security_definitions:
            api_key:
                type: apiKey
                name: api_key
                in: header
        security: 
            api_key: []
```

The best is to look at http://swagger.io/specification/ to know the fields available.

**Comment by wraycode** [comment]
thanks , I've added this to my config, should this give me a headers option in my swagger try it out? if not how do I get it so can add the token to the try it out?

**Comment by wraycode** [comment]
I added this and can send my key but still have to manually add Bearer not sure if this si the bestr practice with JWT or not  application/json works but my return image/jpeg does not retrun image now
`     *     produces={"application/json", "image/jpeg"},
     *     tags={"Render canvas"},
     *     @SWG\Parameter(
     *         name="Authorization",
     *         in="header",
     *         required=true,
     *         type="string",
     *         default="Bearer TOKEN",
     *         description="authorization"
     *     ),  `

**Comment by Alex-D** [comment]
I need to write `securityDefinitions` like in spec.

Also, lock icon is missing, Authorization popup seems broken: no cross to close it.

How can I mark an action as using authorization/security?

I use voters, so I can't use `@Security` annotation :/

**Comment by wraycode** [comment]
LexikJWTAuthenticationBundle

**Comment by davidbonachera** [comment]
Is JWT supported by swagger ?
https://github.com/swagger-api/swagger-ui/issues/3387

**Comment by wraycode** [comment]
you can pass a token in as a header parameter

`     *     @SWG\Parameter(
     *         name="Authorization",
     *         in="header",
     *         required=true,
     *         type="string",
     *         default="Bearer TOKEN",
     *         description="Authorization"
     *     ),   `

**Comment by iBasit** [comment]
I have tried following and so many other solutions, but it is failing to pick up any security settings. I have even installed `dev-master`, but no hope.

```

nelmio_api_doc:
    documentation:
        security_definitions:
            api_key:
                type: apiKey
                name: api_key
                in: header
        security: 
            api_key: []
```

**Comment by GuilhemN** [comment]
@iBasit, is your custom config well exposed? (you can check by looking at the sources of the doc page)

If it is, then that's probably an issue in swagger-ui.

**Comment by iBasit** [comment]
Yes, it is exposed, because configuration info for title, version, and description is working fine, but not the security.

**Comment by GuilhemN** [comment]
`security` field is quite new so it might now be exposed while the rest is.

**Comment by Alex-D** [comment]
You need to change from `security_definitions` to `securityDefinitions`

**Comment by iBasit** [comment]
@Alex-D — Thank you, it start showing "Authorize button" after clicking it shows following:

![image](https://user-images.githubusercontent.com/34341/28852175-27f22992-771f-11e7-8a0d-2c75a19c3a99.png)

After pressing it shows

![image](https://user-images.githubusercontent.com/34341/28852189-3b862fa8-771f-11e7-8c9f-48989cdd933e.png)


But after testing the API call, it does not show api_key in the header definition.

Following is the config I have set it up.

```
    documentation:
        securityDefinitions:
            api_key:
                type: apiKey
                name: api_key
                in: header
            security:
                api_key: [session] 
```

Do you know what I'm missing now or what I'm doing wrong now?

**Comment by Alex-D** [comment]
I think it's a nelmio-api-doc/swagger-ui issue because it does not works for me too.

**Comment by GuilhemN** [comment]
@iBasit are you still using it under `security`?

Also aren't you suppose to define `scheme: Bearer`?

**Comment by noglitchyo** [comment]
@iBasit You have to define the security node as following (note the dash before api_key):
```
security:
            - api_key: []
```
It is because the JavaScript behind expects an array.

However, it remains a problem with the swagger-ui bundle who seems to transform the header name in lower case.. So you get your "Authorization" header as "authorization" which is quite annoying.

**Comment by iBasit** [comment]
@noglitchyo   Can you paste your full configuration settings here. I see you even got name working and `bearer`. 

@GuilhemN I did try `sheme: Bearer` but it didn't work for me, it was actually throwing an error.

**Comment by noglitchyo** [comment]
@iBasit To get the Bearer I put it directly in the api input with my token
This is my full configuration settings:
```yaml
nelmio_api_doc:
    models: { use_jms: false }
    routes:
        path_patterns: 
            - ^/api/[^doc]
    documentation:
        info:
            title: My API
            description: Amazing right?
            version: '0.1'
        securityDefinitions:
            api_key:
                type: apiKey
                description: Your Json Web Token
                name:  Authorization
                in: header
        security:
            - api_key: []
```

**Comment by iBasit** [comment]
No luck! — I have edited the configuration to match with your structure  and nested array in same way, but `request` header still does not have `authorization...`
![image](https://user-images.githubusercontent.com/34341/28925382-a290de30-785c-11e7-96c3-25d86b7a94b4.png)

pop up
![image](https://user-images.githubusercontent.com/34341/28925391-aca954ba-785c-11e7-9728-6fbc654cd7ef.png)

configuration
```
# Nelmio api documentation settings
nelmio_api_doc:
    models: { use_jms: false }
    routes:
        path_patterns: # an array of regexps
            - ^/api
    documentation:
        securityDefinitions:
            api_key:
                description: Your login token
                type: apiKey
                name:  authorization
                in: header
        security:
            - api_key: []
        info:
            title:       API documentation
            description: I wish the settings can be amazing too 
            version: 1.2.0
```

**Comment by iBasit** [comment]
finally working now!. 

I hope they fix few stuff, we have OAuth, so will implement those settings too, later on, see if that works.

**Comment by chucky2305** [comment]
@noglitchyo Can use tell me how you configured a ControllerRoute, where you reused your defined Bearer-Authorization?

**Comment by chucky2305** [comment]
yes the Close-Button is still missing for the Authorization-Overlay

**Comment by Alex-D** [comment]
Yep, you need to add that: https://github.com/Collect-io/Collect.io/blob/develop/back/app/Resources/NelmioApiDocBundle/views/SwaggerUi/index.html.twig#L101

I'm sure it could be done here: https://github.com/nelmio/NelmioApiDocBundle/blob/master/Resources/views/SwaggerUi/index.html.twig

But I did not have time to make a PR for the moment.

**Comment by chucky2305** [comment]
Thanks @Alex-D.
@noglitchyo: i got it working with your config.

**Comment by koftikes** [comment]
What about impliment Bearer Authentication
It should be like basic
https://swagger.io/docs/specification/authentication/bearer-authentication/

Thank you in advance.

**Comment by Alex-D** [comment]
You point the OpenAPI 3.0.0, we are in Swagger 2.0.0 here I guess.

**Comment by GuilhemN** [comment]
Would anyone be interested in writing an article in our docs to help others deal with this ? :)

**Comment by chucky2305** [comment]
I am interested in doing this. But i could start at earliest in february

**Comment by GuilhemN** [comment]
I don't think that's a problem, it would be very nice of you :)

**Comment by chucky2305** [comment]
Since i still have some questions about this, i would like to talk to you
about this upfront in february, okay?

2018-01-10 14:52 GMT+01:00 Guilhem N <notifications@github.com>:

**Comment by GuilhemN** [comment]
Well i'm not sure I'm the best placed to answer your questions about auth but I can do my best to of course.

**Comment by noquepoaqui** [comment]
In case you're interested, i managed to configure oAuth with password flow like this:
```
        securityDefinitions:
            password:
                type: oauth2
                description: provide a password access_token
                flow: password
                tokenUrl: /oauth/v2/token
                name: Authorization
        security:
            - password: []
```

I still get the lower case 'bearer' keyword in the Authorization header making all of the calls fail. As I've got to understand this problems comes out of FOSOAuthServerBundle, as this issue points out:
https://github.com/FriendsOfSymfony/FOSOAuthServerBundle/issues/180

The solution for the ones here working with both bundles, would be to add this to the fosoauth config:

```
fos_oauth_server:
    service:
        options:
            token_type: Bearer
```

**Comment by babaorum** [comment]
@Alex-D you talked about managing security while using voters in your [previous comment](https://github.com/nelmio/NelmioApiDocBundle/issues/1029#issuecomment-316559350).

I'm facing the same problem, the general security part seems to be ok.
But I do not understand, how to get my routes to be defined in the configured secured definitions.

Here is my configuration so far (pretty similar to everything in this post) : 
```yaml

nelmio_api_doc:
    documentation:
        securityDefinitions:
            jwt_token:
                type: apiKey
                name: Authorization
                in: header
        security:
              - jwt_token: []
```

**Comment by koftikes** [comment]
Any update about doc or some help?
on version 2.x my config was: 
```
nelmio_api_doc:
    name: API Documentation
    motd:
        template: 'api_motd.html.twig'
    sandbox:
        authentication:
            delivery: http
            type: bearer
        body_format:
            default_format: json
        request_format:
            formats:
                json: application/json
            method: accept_header

```
when I enter api key: in header was:
Authorization: Bearer ey.......XvG0Gsc

Can someone provide config, doc or etc for version 3.0?

**Comment by koftikes** [comment]
Also in swagger-ui-bundle.js I find next code. As I understand it's means Bearer can be added in Authorization. But how it should be in config?
```
           function i(e) {
                var t = e.request, n = e.securities, r = void 0 === n ? {} : n, i = e.operation,
                    o = void 0 === i ? {} : i, a = e.spec, s = (0, f.default)({}, t), u = r.authorized,
                    l = void 0 === u ? {} : u, p = o.security || a.security || [], h = l && !!(0, c.default)(l).length,
                    m = (0, d.default)(a, ["components", "securitySchemes"]) || {};
                return s.headers = s.headers || {}, s.query = s.query || {}, (0, c.default)(r).length && h && p && (!Array.isArray(o.security) || o.security.length) ? (p.forEach(function (e, t) {
                    for (var n in e) {
                        var r = l[n], i = m[n];
                        if (r) {
                            var o = r.value || r, a = i.type;
                            if (r)
                                if ("apiKey" === a) "query" === i.in && (s.query[i.name] = o),
                                    "header" === i.in && (s.headers[i.name] = o),
                                    "cookie" === i.in && (s.cookies[i.name] = o);
                            else if ("http" === a) {
                                if ("basic" === i.scheme) {
                                    var u = o.username, c = o.password, p = (0, v.default)(u + ":" + c);
                                    s.headers.Authorization = "Basic " + p
                                }
                                "bearer" === i.scheme && (s.headers.Authorization = "Bearer " + o)
                            }
                            else if ("oauth2" === a) {
                                var f = r.token || {}, h = f.access_token, d = f.token_type;
                                d && "bearer" !== d.toLowerCase() || (d = "Bearer"), s.headers.Authorization = d + " " + h
                            }
                        }
                    }
                }), s) : t
            }
```

**Comment by dbu** [comment]
documentation added in #1265

**Comment by WMystral** [comment]
Hello everyone, not sure if it's a bug or not...

I'm getting trouble getting responses from the API in my documentation...

I can get my JWT token easily, but once I'm putting in in the global authentication section, I get this error 

![image](https://user-images.githubusercontent.com/44498811/59109548-893d0a00-893d-11e9-8a36-caaa650a67ed.png)

I'm not getting any error while I'm doing this :

![image](https://user-images.githubusercontent.com/44498811/59109712-d5884a00-893d-11e9-90d7-975fbbaaefb7.png)


And here is my security configuration:

```
        securityDefinitions:
            Bearer:
                type: apiKey
                name: Authorization
                in: header
        security:
            - Bearer: []
```

Also tried this

````
        securityDefinitions:
            Bearer:
                type: apiKey
                name: Authorization
                in: header
        security:
            - api_key: []
```
