### ISSUE TITLE
[3.0] @Model with FOSUser

### ISSUE THREAD

**Issue by ricardo-neves-kununu** [nelmio/NelmioApiDocBundle#1030]
I'm trying to use @Model on my User class from FOSUser Bundle, but I'm getting the following error:

> The PropertyInfo component was not able to guess the type of AppBundle\Entity\User::$plainPassword

This is what I have on my Controller:
`     *     @SWG\Response(`
`     *         response=200,`
`     *         description="Operation Successful",`
`     *         @Model(type=User::class)`
`     *     ),`

I did some debug and seems since this property is not mapped with doctrine and that's why it's not able to find it's type.
I also couldn't find any docs for the @model annotation.
It's possible that I am missing something here, any help would be appreciated.

**Comment by GuilhemN** [comment]
You have to configure what fields from your model will be serialized and you have to allow only fields with known types so that the bundle can determine how is your model.
If you're using the jms serializer, you can use `@Expose`, `@ExclusionPolicy`, etc... If you're using the symfony serializer, you can use `@Groups`.

**Comment by ricardo-neves-kununu** [comment]
Ok, I've used `@Groups` on a simple entity class and it seems to work but have you tried it using on an entity that extends FOSUser Entity class?

**Comment by GuilhemN** [comment]
You can also choose which properties will be serialized using yaml or xml files. This allows to configure the serialization of an entity in a third party library.

**Comment by pdugas** [comment]
Any further thoughts on this one?  I've tried overriding JMS Serializer for FOS\UserBundle\Model\User to no avail.  

```
# app/config/config.yml
jms_serializer:
    metadata:
        auto_detection: true
        directories:
            FOSUserBundle:
                namespace_prefix: FOS\UserBundle
                path: "@AppBundle/Resources/config/serializer"
```

```
#src/AppBundle/Resources/config/serializer/Model.User.yml
FOS\UserBundle\Model\User:
    exclusion_policy: NONE
    properties:
        plainPassword:
            type: string
            exclude: true
```

I suspect I'm not telling JMS\Serializer where to look properly as I can put bogus YAML in there and not get an error other than the one about $plainPassword.
