### ISSUE TITLE
Unable to expose JSON route

### ISSUE THREAD

**Issue by MrNicodemuz** [nelmio/NelmioApiDocBundle#1046]
When I follow the docs and add the following into my routing.yml, I get an error:

```
# app/config/routing.yml
app.swagger:
    path: /api/doc.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger }
```

Error:
```
Unable to parse the controller name "nelmio_api_doc.controller.swagger".
```

What am I doing wrong?
