### ISSUE TITLE
When adding POST - PATCH method is added as well

### ISSUE THREAD

**Issue by eldad87** [nelmio/NelmioApiDocBundle#1089]
Hi,
Branch: `dev-master`.

> config.yml

```
nelmio_api_doc:
    documentation:
        info:
            title: "name"
            description: "description"
            version: 1.0.0
    routes:
        path_patterns: # an array of regexps
            - ^/API
```

> routing.yml
```
NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing/swaggerui.xml"
    prefix:   /API/Doc


REST_User:
    resource: "@AppBundle/Controller/API/UserController.php"
    type: rest
    prefix: /API/{version}/User
    #name_prefix:  api_user_
```

UserController.php
```
/**
 * @Rest\Version("v1")
 *
 * Manage User
 * @package AppBundle\Controller\API
 */
class UserController extends FOSRestController
{

	/**
	 *
	 *
	 *
	 * @Rest\View(serializerGroups={"register"})
	 * @SWG\Post(consumes={"application/json","application/xml"}, path="/Register",
	 *     @SWG\Parameter(
	 *       	name="user",
	 *       	in="body",
	 *       	description="JSON User object",
	 *       	type="json",
	 *       	required=true,
	 *      	@Model(type=User::class, groups={"register"})
	 *     ),
	 *
	 *     @SWG\Response(
	 *         response="200",
	 *         description="Returned when successful.",
	 *         @Model(type=AppBundle\Entity\User::class, groups={"register"})
	 *     )
	 * )
	 *
	 * @ParamConverter("user", converter="fos_rest.request_body")
	 */
	public function RegisterAction(User $user)
```

**Expected result**: There is a new POST API method fully described.
**Actual result** 2 methods are added:
 - POST /Register - Only `user` parameter exists, with FULL JSON description (good thing) of User::class documented.
 - PATCH /API/{version}/User/egister - `version` parameter + `user` exists. This time `user`'s Description is `undefined`.  In addition, the "R" from "**R**egister" is missing in the URL.

Please advise,
Thanks!
