### ISSUE TITLE
[3.0] API Platform + NelmioApiDocBundle prefix issues

### ISSUE THREAD

**Issue by simshaun** [nelmio/NelmioApiDocBundle#1140]
I'm using API Platform + NelmioApiDocBundle.

The API Platform's built-in docs are correct and look like this:
![image](https://user-images.githubusercontent.com/379519/33824698-3d2854ba-de2d-11e7-91e2-4eec8cb51430.png)

And this is what the Nelmio API docs look like. It's adding an extra `/api`.
![image](https://user-images.githubusercontent.com/379519/33824720-50b599d4-de2d-11e7-8aef-e3d4209143c2.png)

My API Platform routing is:

```yaml
api_platform:
    resource: .
    type: api_platform
    prefix: /api
```
