### ISSUE TITLE
RouteMetadataDescriber::getOperations() is NULL

### ISSUE THREAD

**Issue by skhattane** [nelmio/NelmioApiDocBundle#1204]
Hi guys,

my api : Symfony 4.0 + FosRESTBundle 2.3 + NelmioApiDocBundle 3.0 (Twig & assets are installed)
I have this exception when I try to access to the route /documentation (same exception for the default route api/doc)

**Symfony\Component\Debug\Exception\FatalThrowableError" message="Type error: Return value of Nelmio\ApiDocBundle\RouteDescriber\RouteMetadataDescriber::getOperations() must be of the type array, null returned">**

Any ideas ?

**config/packages/fos_rest.yml**
```yaml
fos_rest:
    param_fetcher_listener:
        enabled: true
        force: true

    allowed_methods_listener:
        enabled: true

    routing_loader:
        default_format: json
        include_format: false

    body_converter:
        enabled: true
        validate: true
        validation_errors_argument: violations

    serializer:
        serialize_null: true

    view:
        view_response_listener:
            enabled: true
            force: true
        formats:
            json: true
            xml: true
        jsonp_handler: ~

    body_listener:
        enabled: true
        default_format: json
        throw_exception_on_unsupported_content_type: false

    format_listener:
        enabled: true
        rules:
            - { path: ^/, priorities: [json, xml], fallback_format: json, prefer_extension: false}
```

**config/packages/nelmio_api_doc.yaml**
```yaml
nelmio_api_doc:
    documentation:
        info:
            title: App API
            description: App API
            version: 1.0.0
    routes: # to filter documented routes
        path_patterns:
            - ^/(?!documentation$) # Accepts routes under / except /documentation
```

**config/routes/nelmio_api_doc.yaml**
```yaml
app.swagger_ui:
    path: /documentation
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }
```
**src/Controller/ApplicationController.php**
```php
<?php

namespace App\Controller;

use App\Entity\Application;
use App\Repository\ApplicationRepository;
use Doctrine\ORM\EntityManagerInterface;
use FOS\RestBundle\Controller\Annotations as REST;
use FOS\RestBundle\View\View;
use Nelmio\ApiDocBundle\Annotation\Model;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter as PARAMCONVERTER;
use Swagger\Annotations as SWG;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Validator\ConstraintViolationListInterface;

/**
 * Class ApplicationController
 * @package App\Controller
 */

class ApplicationController
{
    /**
     * @param ApplicationRepository $applicationRepository
     * @return null|array
     *
     * @SWG\Response(
     *     response=200,
     *     description="Return a collection of applications",
     *     @SWG\Schema(
     *         type="array",
     *         @Model(type=Application::class)
     *     )
     * )
     *
     * @REST\View
     */
    public function getApplications(ApplicationRepository $applicationRepository)
    {
        return $applicationRepository->findAll();
    }
```
