### ISSUE TITLE
Controller not found: service "nelmio_api_doc.controller.swagger_ui" does not exist.

### ISSUE THREAD

**Issue by GermanKrutov** [nelmio/NelmioApiDocBundle#1220]
```
composer create-project symfony/skeleton restapi
cd restapi
composer require nelmio/api-doc-bundle
```

In Kernel:
```
return [
    Symfony\Bundle\FrameworkBundle\FrameworkBundle::class => ['all' => true],
    Nelmio\ApiDocBundle\NelmioApiDocBundle::class => ['all' => true],
];
```

In routing:
```
app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

app.swagger:
    path: /api/doc.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger }
```

I open http://localhost:8000/api/doc and see: 
```
(1/1)                                         LogicException                                                                          Controller not found: service "nelmio_api_doc.controller.swagger_ui" does not exist.
--
in ContainerControllerResolver.php (line 75)
at ContainerControllerResolver->createController('nelmio_api_doc.controller.swagger_ui')in ControllerResolver.php (line 43)
at ControllerResolver->createController('nelmio_api_doc.controller.swagger_ui')in ControllerResolver.php (line 69)
at ControllerResolver->getController(object(Request))in ContainerControllerResolver.php (line 41)
at ContainerControllerResolver->getController(object(Request))in HttpKernel.php (line 132)
at HttpKernel->handleRaw(object(Request), 1)in HttpKernel.php (line 66)
at HttpKernel->handle(object(Request), 1, true)in Kernel.php (line 190)
at Kernel->handle(object(Request))in index.php (line 37)
```

But it http://localhost:8000/api/doc.json works fine!
