### ISSUE TITLE
`@SWG\{operation}()` not working properly with controller inheritance

### ISSUE THREAD

**Issue by phansys** [nelmio/NelmioApiDocBundle#1255]
I'm using the annotation `FOS\RestBundle\Controller\Annotations\Get` in order to define routes. While deprecating some features, my API has at least 2 versions coexisting at same time, so I use the `condition` parameter to define a constraint at "Accept" header in order to allow clients to choose which API to consume:
```yaml
# routing.yml
user_v2:
    type: rest
    resource: Controller\Rest\V2\UserController
    options:
        expose: true

user_v1:
    type: rest
    resource: Controller\Rest\V1\UserController
    options:
        expose: true
```
```php
class UserV2 extends FOSRestController
{
    /**
     * @Get("/user", condition="request.headers.get('Accept') matches '/;version=v2([;]|$)/i'")
     */
    public function getUserAction() {}
}
```
```php
class UserV1 extends UserV2
{
    /**
     * @Get("/user", condition="not(request.headers.get('Accept') matches '/;version=v[0-9]/i') or request.headers.get('Accept') matches '/;version=v1([;]|$)/i'")
     */
    public function getUserAction() {}
}
```
This works pretty good with my stable setup and `nelmio/api-doc-bundle (2.13.3)`. Now I'm trying to update to version 3.x, but I'm facing `E_USER_NOTICE` errors like `Unable to merge @SWG\Get() in UserController->getUserAction()`.
