### ISSUE TITLE
Array of objects inside of another object in response

### ISSUE THREAD

**Issue by kunicmarko20** [nelmio/NelmioApiDocBundle#1270]
I am sorry if there is already an issue open for this, I went through issues but I did not find a similar one.

Currently, I have this:

```
     *     @SWG\Response(
     *         response="200",
     *         description="Returned when successful",
     *         @Model(
     *             type=Brand::class,
     *             groups={
     *                  "brandComplete",
     *                  "sourceComplete"
     *             }
     *         )
     *     ),
```
My Brand Entity Is connected to Source. (`OneToMany`)

And my serializers look like:

```
App\Entity\Brand:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            groups: [brandComplete, brandMinimal]
            type: integer
        name:
            expose: true
            groups: [brandComplete, brandMinimal]
            type: string
        sources:
            expose: true
            groups: [brandComplete]
```
```
App\Entity\Source:
    exclusion_policy: ALL
    virtual_properties:
        getChildBrandId:
            expose: true
            groups: [sourceComplete, sourceMinimal]
            serialized_name: childBrand
        getChannelsId:
            expose: true
            groups: [sourceComplete, sourceMinimal]
            serialized_name: channels
```

In my documentation I see:

```
{
  "id": 0,
  "name": "string",
  "sources": [
    {}
  ]
}
```
I expect to see also fields I added to my serialization definition in `sources` but it is empty.

I am probably missing something stupid but I am not sure what, thank you for keeping this bundle alive, just migrated to 3.x it is 👌

**Comment by kunicmarko20** [comment]
I was missing types in my serializer file:

```
App\Entity\Source:
    exclusion_policy: ALL
    virtual_properties:
        getChildBrandId:
            expose: true
            groups: [sourceComplete, sourceMinimal]
            type: integer
            serialized_name: childBrand
        getChannelsId:
            expose: true
            groups: [sourceComplete, sourceMinimal]
            type: array<integer>
            serialized_name: channels
```

As I said already `I am probably missing something stupid` 😄
