### ISSUE TITLE
How to reference response schema from file in NelmioApiDocBundle v3

### ISSUE THREAD

**Issue by meridius** [nelmio/NelmioApiDocBundle#1272]
The old NelmioApiDocBundle v2 could read the response schema from file when you just provided the file name to API method PHPDoc like this:

```
    /**
     * {
     *      "text":"Json Schema for Valid Response",
     *      "schema":"basket.json"
     * }
     */
    public function myApiMethod() {}
```

I know that you can define the schema in new v3 like this:

```
    /**
     * @Operation(
     *     tags={"Checkout - Basket"},
     *     summary="Returns requested Basket",
     *     @SWG\Response(
     *         response="200",
     *         description="Returned when successful",
     *         @SWG\Schema(ref="#definitions/checkout_basket"),
     *     ),
     * )
     */
```

and define the reference in the Nelmio bundle config like this:

```
nelmio_api_doc:
    documentation:
        definitions:
            checkout_basket:
                type: object
                properties:
                    success:
                        type: boolean
                        example: false
                    error:
                        type: string
                        example: message
```

So I tried it with file, but I can't figure out what the right path to the JSON should look like.

```
nelmio_api_doc:
    documentation:
        definitions:
            checkout_basket:
                type: file
                ref: ../../../src/validator/basket.json
```
