### ISSUE TITLE
Documenting actions from third-party bundles

### ISSUE THREAD

**Issue by zablik** [nelmio/NelmioApiDocBundle#1275]
Hi all,

In my application I use FOSOAuthServerBundle and I've imported routes from this bundle

``` yml
# app/config/routing.yml
fos_oauth_server_token:
    path:     /v2/token
    defaults: { _controller: fos_oauth_server.controller.token:tokenAction }
    methods:  [GET, POST]`
```

The problem is that inside of the bundle those actions are not annotated, so there is no information about them in my documentation 
![screenshot_30](https://user-images.githubusercontent.com/6074433/37869396-b5bb694e-2fc7-11e8-9d5a-1a4b83dbdbf9.png)

Is it possible to attach documentation to the routes that have been imported?

Thanks!
