### ISSUE TITLE
TypeError: t.get is not a function on auth button

### ISSUE THREAD

**Issue by eugenekurasov** [nelmio/NelmioApiDocBundle#1280]
I have JS exception when click auth on action where I overrides security.
<img width="344" alt="t_get_is_not_a_function" src="https://user-images.githubusercontent.com/7052418/38196116-e3bc42aa-3689-11e8-939e-95bf033e7bd1.png">

```
composer show | grep nelmio
nelmio/api-doc-bundle                    v3.2.0
```
Sample config for securityDefinitions
```
Auth:
    type: apiKey
    description: x-auth-token.
    name: X-AUTH-TOKEN
    in: header
Auth2:
    type: apiKey
    description: x-auth-token2.
    name: X-AUTH-TOKEN
    in: header
```
Sample annotation
```
@Operation(
     tags={"tag"},
     summary="summary",
     security={"Auth2"}
)
```
