### ISSUE TITLE
Model properties name parsing don't use my symfony serializer name_converter

### ISSUE THREAD

**Issue by florianajir** [nelmio/NelmioApiDocBundle#1324]
I use the built-in symfony serializer with this config:

```yaml
framework:
    serializer:
        name_converter: 'serializer.name_converter.camel_case_to_snake_case'
```

but my models documentation are still showing camelCased properties.

I saw this bundle uses PropertyInfo component to parse model but I didn't find a way to configure it to use name converter like the serializer.

Please tell me there's a solution for this common problem ?!
