### ISSUE TITLE
Authentication with JWT Bearer

### ISSUE THREAD

**Issue by juju95** [nelmio/NelmioApiDocBundle#1335]
Hi everyone, 
I'm updating a project to ApiDoc v3 and i can't find a working solution to add JWT authentication on it ...
Found lot of messages of persons getting the same problem but i currently don't seen anything resolved ( only add "Bearer" before the JWT in the input manually ... not terrible ... )

I can make it word with a type = apiKey but then i don't have the Bearer.
When i check the swagger-ui.js

I see that only basic and apiKey are enabled ( i found some doc saying to use type = http ) but it is not enabled in the swagger ui ( only basic and apiKey again, else, it return the default "Unknown security definition type" )

So i'm totally in the different versions of documentations / help about it ...
Is there a way to have it done properly ( without manually modifying the JS etc. ) ? Or do i have to rollback to 2.0 to have it working properly again ? 

Thanks in advance for your Help

**Comment by lsv** [comment]
`
* @SWG\Parameter(
     *     name="Authorization",
     *     in="header",
     *     required=true,
     *     type="string",
     *     default="Bearer TOKEN",
     *     description="Bearer token",
     * )
`

I use this on my routes where token is required.
Can also be added on a whole controller

**Comment by KiSchulte** [comment]
Hi,

the above solution is not working for me.
I followed the config description, here is my configuration:

```
nelmio_api_doc:
    documentation:
        schemes: [http]
        info:
            title: Maplingo backend API
            description: All neccessary Endpoints for maplingo
            version: 1.0.1

        securityDefinitions:
            Bearer:
                type: apiKey
                description: 'Value: Bearer {jwt}'
                name: Authorization
                in: header
        security:
            - Bearer: []
```

In the Methode annotation:
```
    /**
     * @Get("/provider/city-list")
     * @Options("/provider/city-list")
     *
     * @SWG\Response(response="200", description="list of existing providers cities")
     * @SWG\Tag(name="provider")
     * @Security(name="Bearer")
     *
     * @return JsonResponse
     */
```
But still no Beraer Key Word in the request:
```
curl -X GET "http://localhost:8000/api/provider/city-list" -H "accept: application/json" -H "Authorization: YjBkZDVjOWEwMTI4YjkwNzhlMmIzNzYwNjNhN2QzNzMzOGJjZDk2NmZlYTY4NTMyMjRiNWYwNGU1N2FiMzFiMA" 
```

Any idea what could be wrong here or the reason for this?

**Comment by KiSchulte** [comment]
So, I guess the only solution is to add it in the Authorized Input manually.

**Comment by atlance** [comment]
https://tools.ietf.org/html/rfc6750

**Comment by KiSchulte** [comment]
Actually, I solved it now with https://github.com/nelmio/NelmioApiDocBundle/issues/1029#issuecomment-357753429
WHich is working like charm

**Comment by PHPTCloud** [comment]
my security service accept `Authorization` header and trying authenticate user, so for define this header in swagger i need configure api like this

`/config/packages/nelmio_api_doc.yaml`

```yaml
nelmio_api_doc:
  documentation:
    info:
      title: API name
      version: 1.0.0
    securityDefinitions:
      Authorization:
        type: apiKey
        name: Authorization
        in: header
    security:
        - Authorization: []
  areas:
    path_patterns:
      - ^/api

```

**Comment by chrisguitarguy** [comment]
Couple good answer here, but another one for open API v3 and the 4.X release of the bundle.

```yaml
nelmio_api_doc:
  # ...
  documentation:
    security:
      - jwt: []
    components:
      securitySchemes:
        jwt:
          type: apiKey
          in: header
          name: Authorization # or another header name
```

OpenAPI documentation:

- https://swagger.io/docs/specification/authentication/
- https://swagger.io/docs/specification/authentication/api-keys/
