### ISSUE TITLE
The option "path_patterns"

### ISSUE THREAD

**Issue by LaetitiaCarpentier** [nelmio/NelmioApiDocBundle#1352]
Hello,

Strange issue when I try to configure path patterns :

> The option “path_patterns” with value array is expected to be of type “string[]“, but is of type “string[]”

> app/config/routing.yml

```
app.swagger_ui:
   path: /api/docs
   methods: GET
   defaults: { _controller: nelmio_api_doc.controller.swagger_ui }
```

> app/config/config.yml

```
nelmio_api_doc:
   documentation:
       info:
           title: My app
           description: This is an awesome app!
           version: 1.0.0
   areas:
       path_patterns:
           - ^/api(?!/docs$)
```

If you have any idea of how to solve that, it would be nice !
I'm on Symfony 4.
Thanks,
