### ISSUE TITLE
[JMSModelDescriber] Serialization config for nested arrays generates invalid definitions

### ISSUE THREAD

**Issue by phansys** [nelmio/NelmioApiDocBundle#1364]
I need to generate documentation for a property which holds values like `[[0, 0.5], [0, 0.8]]`, so I have the following serializer configuration which works fine for serialization purposes:
```yml
# config/serializer/MyObject.yml
MyObject:
    exclusion_policy: ALL
    properties:
        data:
            expose: true
            inline: false
            type: array<array<float>>
```
The problem is that config doesn't generate a valid OpenAPI definition (note the missing "items" property for `MyObject.properties.data.items`):
```yml
definitions:
  MyObject:
    properties:
      data:
        items:
          type: array
        type: array
    type: object
```
It should look like:
```yml
definitions:
  MyObject:
    properties:
      data:
        items:
          items:
              type: number
          type: array
        type: array
    type: object
```
So, https://editor.swagger.io/# shows me the following error:
```
Semantic error at definitions.MyObject.properties.data.items
Schemas with 'type: array', require a sibling 'items: ' field
```
I was trying to play with `JMSModelDescriber::describe()` in order to let the describer to follow nested array definitions, but I couldn't reach my goal.
Even, as a workaround I also tried to override the definition for `MyObject` at `nelmio_api_doc.documentation.definitions.MyObject`, but this causes the original definition to be renamed to "MyObject2", keeping the invalid schema.
I'm able to create a WIP PR with some of my attempts if this report seems right. Thank you in advance.
