### ISSUE TITLE
Serialization groups are not passed on to nested Entities

### ISSUE THREAD

**Issue by chriskaya** [nelmio/NelmioApiDocBundle#1383]
Hi there,

On current master I have an issue were the Default serialization group is not passed on to nested Entities.
It seems to be caused by PR #1367 (more precisely by commit #5e5c650cf8b209da1b46d83c2c451fcd25d741c0).

Here's an example:

```
App\Entity\Transaction:
    exclusion_policy: ALL
    xml_root_name: transaction
    properties:
        id:
            expose: true
        name:
            expose: true
        category:
            expose: true
        buyer:
            expose: true
            groups: [ 'transaction_full' ]
```

```
App\Entity\Category:
    exclusion_policy: ALL
    xml_root_name: category
    properties:
        id:
            expose: true
        name:
            expose: true
        transactions:
            expose: true
            groups: [ 'category_full' ]
```

```
/**
     * Creates a transaction
     *
     * @SWG\Response(
     *     response=201,
     *     description="Transaction created",
     *     @Model(type=Transaction::class, groups={"Default"})
     * )
     * @SWG\Tag(name="Transaction")
     */
```

Result before #1367:
```
{
  "id": 0,
  "name": "string",
  "category": {
    "id": 5,
    "name": "Vente d'objets",
  }
}
```

Result after  #1367:
```
{
  "id": 0,
  "name": "string",
  "category": {
      "id": 5,
      "name": "Vente d'objets",
      "transactions": [
            {
              "id": 0,
              "name": "string",
              "category": null,
              "buyer": { ... }
            }
      ]
  }
}
```

As you can see, the "Default" group is lost in nested Entities, and everything is rendered.
BTW, with stable (3.2.1), I must specify "Default" otherwise everything is shown (not only in nested Entities).

So for me, `$groups = null` (#5e5c650cf8b209da1b46d83c2c451fcd25d741c0) is not the same as `$groups = [self::DEFAULT_GROUP]` (https://github.com/schmittjoh/serializer/blob/942b566c801b2c567193f006ebf95b027e5bd439/src/JMS/Serializer/Exclusion/GroupsExclusionStrategy.php#L85).

Or maybe I'm missing something?

Thx for your time :)

**Comment by goetas** [comment]
You sure about this? you are referring to #1367 (that is a nemio api doc PR) while your error is related to jms/serializer... 

Are you passing the group to the serializer? (this depends how you are using jms... if via FOSRest or something else... can you share a bit ore about your controller?

**Comment by chriskaya** [comment]
Yes I'm starting to think there is something wrong in my conf...
I posted that here because switching to master caused this change in my documentation, and if I comment `$groups = null` it works again.

I'm using SF 4.1, with FOSRest 2.3 and JMS 2.3
Here's my JMS conf:
```
jms_serializer:
    visitors:
        xml:
            format_output: '%kernel.debug%'
    metadata:
        auto_detection: true
        directories:
            Entity:
                namespace_prefix: "App\\Entity"
                path: "%kernel.root_dir%/../config/serializer"
```

And my FOSRest conf:
```
fos_rest: 
    param_fetcher_listener:  true
    allowed_methods_listener:  true
    routing_loader: true
    view:
        view_response_listener:  true
        formats:
            json : true
        templating_formats:
            html: true
    exception:
        codes:
            Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException: 403
        messages:
            Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException: true
    format_listener:
        rules:
            - { path: ^/api, prefer_extension: true, fallback_format: json, priorities: [ json ] }
            - { path: ^/oauth, prefer_extension: true, fallback_format: json, priorities: [ json ] }
```

Also, nelmio conf:
```
nelmio_api_doc:
    documentation:
        host: 'platform.kayanet.fr'
        schemes: [ 'https' ]
        consumes: [ 'application/json' ]
        produces: [ 'application/json' ]
        info:
            title: 'Tripartie backend'
            description: 'Everything is awesome!'
            version: 1.0.0
    areas:
        path_patterns:
            - ^/api(?!/doc$)
```
