### ISSUE TITLE
Annotation to ignore action

### ISSUE THREAD

**Issue by aequasi** [nelmio/NelmioApiDocBundle#1414]
Would be nice to have an annotation that would mark a controller action as ignored, as an alternative to altering the regex like: 

```
nelmio_api_doc:
    areas:
        path_patterns:
            - ^/(?!docs|admin|_(profiler|error|wdt)|login|$)
```

Being able to just have:

```
    /**
     * @Route("/login")
     * @Ignore()
     */
    public function loginAction() {
	    // ...
    }
```
