### ISSUE TITLE
Document a route generated by a third party bundle

### ISSUE THREAD

**Issue by ThomasLabstep** [nelmio/NelmioApiDocBundle#1426]
Hi!

I'm using OneUpUploaderBundle and I want to document the upload endpoint.

The routing looks like this:
```
oneup_uploader:
    path: /api/generic/file/upload
    defaults: { _controller: oneup_uploader.controller.labstep:upload }
    methods: [POST, PUT, PATCH]
```

Should I extend the controller just to setup the documentation syntax, or is there a way to do this in yml ?

Thanks!
