### ISSUE TITLE
Unable to use documentation decorator with API Platform

### ISSUE THREAD

**Issue by elkangaroo** [nelmio/NelmioApiDocBundle#1462]
We wanted to decorate the `api_platform.swagger.normalizer.documentation` service as documented at https://api-platform.com/docs/core/swagger#overriding-the-swagger-documentation to define some recurring parameters and easily reference them in all our resources.

The service is defined like this:
```
  App\Serializer\SwaggerDocumentationDecorator:
    autoconfigure: false
    decorates: 'api_platform.swagger.normalizer.documentation'
    arguments:
      $decorated: '@AppSerializer\SwaggerDocumentationDecorator.inner'

```

This works with the default Swagger UI shipped with API Platform, but unfortunately throws an exception when using the NelmioApiDoc:

```php
Argument 2 passed to Nelmio\ApiDocBundle\Describer\ApiPlatformDescriber::__construct() must be an instance of 
ApiPlatform\Core\Swagger\Serializer\ApiGatewayNormalizer or 
ApiPlatform\Core\Swagger\Serializer\DocumentationNormalizer, 
App\Serializer\SwaggerDocumentationDecorator given.
```

So the problem is, the constructor of \Nelmio\ApiDocBundle\Describer\ApiPlatformDescriber only allows exactly those 2 normalizers and fails on everything else.

Is there another way to define parameters in the global parameters section of OpenAPI?
