### ISSUE TITLE
How to hide Api-plaform Docs from Nelmio Docs

### ISSUE THREAD

**Issue by GermanKrutov** [nelmio/NelmioApiDocBundle#1484]
I hope someone could help me to use Api-platorm with Nelmio.
I use Api-plaform and Nelmio. I need to hide the Api-platform docs from Nelmio.
I need to have 3 routes:

- /internal -> API-Platform Docs
- /external -> NELMIO-Docs
- /admin -> NELMIO-Docs

My config:
```
# config/packages/nelmio_api_doc.yaml
nelmio_api_doc:
    documentation:
        info:
            title: ...
            description: ...
            version: 0.2.0
    areas: # to filter documented areas
        default:
            path_patterns: [ ^/external ]
        external:
            path_patterns: [ ^/external ]
        admin:
            path_patterns: [ ^/admin ]
```
```
# config/routes/nelmio_api_doc.yaml
app.swagger:
    path: /{area}/json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger, area: default }

app.swagger_ui:
    path: /{area}
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui, area: default }
```
```
# config/routes/api_platform.yaml
api_platform:
    resource: .
    type: api_platform
    prefix: /internal/
```

But if I go to http://localhost/external or http://localhost/admin I see always not only needed routes, but also the routes from API-Platform:

![Auswahl_253](https://user-images.githubusercontent.com/29118092/54421723-53f19900-470d-11e9-8b51-4a7d27888d8f.jpg)
