### ISSUE TITLE
How to use custom Normalizer or NameConverter ?

### ISSUE THREAD

**Issue by nlhommet** [nelmio/NelmioApiDocBundle#1491]
Hi,
How to use custom Normalizer or NameConverter ?
I need to add in output Model custom attributes.
I have created a custom ObjectNormalizer with CamelCaseToSnakeCaseNameConverter, but I can not implement it in my swagger doc.

I do not use JMS and api-platform.
tx.

**Comment by GuilhemN** [comment]
Sorry for answering so lately...

https://github.com/nelmio/NelmioApiDocBundle/pull/1636 introduced the possibility to take into account a name converter, and notably a custom one.
You may register it using:
```yaml
framework:
    serializer:
        name_converter: your_custom_service_id
```

About a custom normalizer, since we can't know how it behaves, the only possibility I see is to implement a custom model describer (see https://github.com/nelmio/NelmioApiDocBundle/tree/master/ModelDescriber).

**Comment by VBelozyorov** [comment]
Hi @GuilhemN!
My custom Normalizer for class takes normalization result based on Symfony\Serializer annotations and just adds some more fields to this result.
So while implementing ModelDescriber for this class I want this describer would be responsible only for those added fields and others would come from annotations inside class.

I've tried to inject \Nelmio\ApiDocBundle\ModelDescriber\ObjectModelDescriber (@nelmio_api_doc.model_describers.object) inside my describer to behave like this:

    public function describe(\Nelmio\ApiDocBundle\Model\Model $model, \OpenApi\Annotations\Schema $schema)
    {
        $this->objectModelDescriber->describe($model, $schema);

        $schema->properties[] = new \OpenApi\Annotations\Property([
            'property' => 'property_from_normalizer',
            'type' => 'string'
        ]);
    }

And for one of my classes this approach seems working ok, but for another class I've faced with this:

Argument 2 passed to Nelmio\ApiDocBundle\ModelDescriber\Annotations\AnnotationsReader::__construct() must be an instance of Nelmio\ApiDocBundle\Model\ModelRegistry, null given, called in /var/www/app/vendor/nelmio/api-doc-bundle/ModelDescriber/ObjectModelDescriber.php on line 70

Any idea why same approach works different for different cases here? Maybe there is more correct solution for this?

**Comment by GuilhemN** [comment]
@VBelozyorov yes your final solution is correct.
We will most likely try to get rid of the `*Aware` model but unfortunately it's not done yet, so for now this is the only way to have it working :/

**Comment by kosmala007** [comment]
You can overwrite ``Nelmio\ApiDocBundle\ModelDescriber\ObjectModelDescriber`` arguments:
```yaml
    Nelmio\ApiDocBundle\ModelDescriber\ObjectModelDescriber:
        arguments:
            $mediaTypes: []
            $propertyDescribers: !tagged_iterator nelmio_api_doc.object_model.property_describer
            $nameConverter: '@serializer.name_converter.camel_case_to_snake_case'
        tags: [nelmio_api_doc.model_describer]
```
