### ISSUE TITLE
Ability to mark external route as deprecated in yaml

### ISSUE THREAD

**Issue by florianajir** [nelmio/NelmioApiDocBundle#1519]
Hello,

I try to find a way to load oauth token routes and mark the GET version as deprecated. There's no problem to achieve it for my project endpoint but I don't know how to do it for an external route configuration w/ yaml

What I want to achieve: (not working)

```yaml
fos_oauth_server_token_post:
    path: /oauth/v2/token
    methods: [POST]
    defaults: { _controller: fos_oauth_server.controller.token::tokenAction }

fos_oauth_server_token_get:
    path: /oauth/v2/token
    methods: [GET]
    options: { deprecated: true }
    defaults: { _controller: fos_oauth_server.controller.token::tokenAction }
```
