### ISSUE TITLE
Documentation of Areas

### ISSUE THREAD

**Issue by andydandy80** [nelmio/NelmioApiDocBundle#1533]
How to describe areas, whats the correct way?
You wrote it was fixed in #1307 and #1404, but in current version its not working, why removed code?

Thats not working for me (v3.4.0):
```
nelmio_api_doc:
    areas:
        default:
            path_patterns: [ ^/api/route1 ]
            documentation:
                description: "This is the documentation for route1"
            with_annotation: true
        test:
            path_patterns: [ ^/api/route2 ]
            documentation:
                description: "This is the documentation for route2"
            with_annotation: true
```
