### ISSUE TITLE
Tags and Areas

### ISSUE THREAD

**Issue by andydandy80** [nelmio/NelmioApiDocBundle#1534]
I´m working with areas in my documentation to separate it. In the Config "nelmio_api_doc.yaml" i wrote:

```

nelmio_api_doc:
    areas:
        area1:
            path_patterns: [ ^/api/route1 ]
            documentation:
                info:
                    description: "This is the documentation for route1"
            with_annotation: true
        area2:
            path_patterns: [ ^/api/route2 ]
            documentation:
                info:
                    description: "This is the documentation for route2"
            with_annotation: true
```

```
        tags:
            - name: "Tag1"
              description: "Description 1"
            - name: "Tag2"
              description: "Description 2"
```
Tag1 belongs to area1 and Tag2 to area2.
Now when i call the docs for area1, the Tag1 will be rendered correctly, but it also renders an empty block for Tag2, thats not correct.
Inversely it renders Tag1 empty, Tag2 correct.

I hope to have explained it understandably my problem.
