### ISSUE TITLE
How to set Nelmio Doc with a custom JMS Serializer Handler

### ISSUE THREAD

**Issue by rliebi** [nelmio/NelmioApiDocBundle#1546]
This is a question I have already asked on stack overflow a few days ago, but did not get an answer for. I therefore also post it here.
see: https://stackoverflow.com/questions/58078812/how-to-set-nelmio-doc-with-a-custom-jms-serializer-handler

In the generated NelmioApiBundle my relations are displayed as {} instead of 0.

I use a custom JMS Handler for Object Relations. (RelationHandler)

On my relations I specify a special Class as type in the given Model (ChildRelation). The handler then manages the conversion from Object to ID. This works great for JMS Serializer but not for the corresponding Nelmio API Doc

I have tried to mess with @SWG\Schema directly on ChildRelation but this did not work

In this example role is technically a UserRole Object which inherits from Concrete.

```
## serializer/Model.DataObject.User.yml
AppBundle\Model\DataObject\User:
    access_type: public_method
    properties:
        capabilities:
            groups: [detailed, data]
            type: array<string>
        role:
            groups: [detailed, list, data, create, update]
            type: AppBundle\Model\DataObject\ChildRelation
```
```
// RelationHandler Serializer:
final class RelationsHandler implements SubscribingHandlerInterface
{
 (...)
public function serializeConcreteToId(JsonSerializationVisitor $visitor, Concrete $concrete, array $type, SerializationContext $context
    ) {
        return $concrete->getId();
    }
}
```
I expect to get the same model as I get when calling the endpoint.

```
{
  "role": 271,
  "capabilities": []
}
```
But in swagger the response looks like this:

```
{
  "capabilities": [],
  "role": {}
}
```
Is there a nice way to do this?
