### ISSUE TITLE
documentation_uri option doesn't work in 3+

### ISSUE THREAD

**Issue by OneEyedSpaceFish** [nelmio/NelmioApiDocBundle#1549]
Hello there!

Internally I'm using paths in a format of  `/test/endpoint`, but externally these endpoints are hosted as `/v1/test/endpoint` via apache.

Nelmio uses the routes annotation or the `routes.yaml` config file, which is right for symfony internally, but externally those routes will have a prefix of `/v1`. For this reason, the generated json file and the openapi uris are incorrect, and will the requests made from the sandbox will result in a `404`.

It would be great if we had a feature to specify an external path for these endpoints or an optional:
```
test.endpoint.get:
    path: /test/endpoint
    defaults:
        _controller: App\Controller\TestController::getTestResponse
    methods: [GET]
    options:
        documentation_uri: /v1/test/endpoint
```
option.

This then could be used to overwrite the original path from the routing if need be.

Edit:
FYI; If the specs could be agreed upon, and if I'd be pointed to the right direction, I wouldn't mind making this change and opening a PR for this.

**Comment by GuilhemN** [comment]
We're using `$request->getBaseUrl()` to get the base path so it should normally contain the path rewritten by Apache (see https://github.com/nelmio/NelmioApiDocBundle/blob/master/Controller/DocumentationController.php#L53).

Could you check what value does it contain for you please ?

In any case, reimplementing `documentation_uri` as a controller option would be acceptable for me. It would mostly be about updating https://github.com/nelmio/NelmioApiDocBundle/blob/master/Controller/DocumentationController.php#L53 and https://github.com/nelmio/NelmioApiDocBundle/blob/master/Controller/SwaggerUiController.php#L60.

**Comment by spolischook** [comment]
It seems that this issue still not resolved.
Should I make a PR for that?

**Comment by spolischook** [comment]
Ok, the solution as simple as possible:
```yaml
nelmio_api_doc:
    documentation:
        basePath: '/v1.0/mailer'
```
Actually any key under `documentation` will be passed as native Swagger doc option
