### ISSUE TITLE
Authentication JWT token bearer

### ISSUE THREAD

**Issue by timotheemoulin** [nelmio/NelmioApiDocBundle#1566]
Hello,

I'm facing an issue with the configuration of the authentication bearer.

My application implemented JWT token authentication by passing the JWT token in the *Authorization* header with the format `Bearer {jwt}`.

How can I specify the format of the header value with Nelmio?

Here is the expected header 
`curl -H "Authorization: Bearer {this-is-my-jwt-token}"`
but instead I have `-H "Authorization: {this-is-my-jwt-token}"`.

Here is my Nelmio config.

```
nelmio_api_doc:
  documentation:
    securityDefinitions:
      Bearer:
        type: apiKey
        description: 'Authorization: Bearer {jwt}'
        name: Authorization
        in: header
        scheme: Bearer
    security:
      - Bearer: []
  areas: # to filter documented areas
    path_patterns:
      - ^/api
```

Any idea on how to configure it?

Thanks for the support
tim
