### ISSUE TITLE
Different routes for the same controller

### ISSUE THREAD

**Issue by andrii-pez** [nelmio/NelmioApiDocBundle#1571]
Hi!
Here is a question: let's imagine I have one controller ApiController.php which is responsible for two groups:
```php

/**
 * @Route("/{area<admin|front>}/api")
 */
class ApiController
{
     /**
     * @Route("/get-something", name="foo", methods={"GET"})
     */
    public function getSomething(): Response
    {
        ....
    }

    ....
}
```
and my nelmio_api_doc file:

```yaml
nelmio_api_doc:
    areas:
        admin:
            path_patterns: 
                 - ^/{area}/api/get-something
        front:
            path_patterns: 
                 - ^/{area}/api/get-something

```

as a result I have two pages with docs:
- /api/doc/admin
- /api/doc/front

which display this route with description on both pages as: 
> /{area}/api/get-something

Is this possible  to display them as:
> /admin/api/get-something on /api/doc/admin

and 
> /front/api/get-something on /api/doc/front

?

Thank you in advance!

**Comment by GuilhemN** [comment]
Have you tried splitting the route annotation on your class to :
```
/**
 * @Route("/front/api")
 * @Route("/admin/api")
 */
```
?

**Comment by andrii-pez** [comment]
Yes, I have
it works correctly, but only for first annotation `@Route("/front/api")` and second one `@Route("/admin/api")` is ignored 😔

**Comment by chrisguitarguy** [comment]
The bundle is seeing `{area}` as a route parameter which is expected and generating docs accordingly. I'd suggest _maybe_ mounting the controller via yaml or xml?

```
_admin:
  prefix: /admin
  resource: '../src/Controller/THeController.php'
  type: annotation
```

I don't think we'd be able to really know how to reach in and replace `{area}` correctly. And having it be based on the specific name `{area}` seems awfully magical.
