### ISSUE TITLE
How to describe object properties when using jmsserializer config ?

### ISSUE THREAD

**Issue by kriks57** [nelmio/NelmioApiDocBundle#1574]
Hi,

first of all, thanks for your bundle !

We use `ref=@Model(type=Object::class)` with our JMSSerializer configuration (in yml files) and it works well to output the good type !

But we couldn't find a way to add a description and example for properties that are on the propel base class, except by adding the properties on the child class too, which does not seem to be a good solution.
Also how is it possible to give description and example for methods use in serializer config (virtual_properties)

Thanks

**Comment by lukepass** [comment]
I am interested in this topic too. Method descriptions are not applied to VirtualProperty annotations.

**Comment by GuilhemN** [comment]
A solution could be to add them in your config:
```yaml
nelmio_api_doc:
    documentation:
        definitions:
            Object:
                type: object
                properties:
                    bar: { description: this is bar }
    models:
        names:
            - { alias: Object, type: Object::class} # Enforces the name Object is used
```

Is this good enough for you use case?
