### ISSUE TITLE
symfony web debug toolbar does not appear anymore

### ISSUE THREAD

**Issue by florianajir** [nelmio/NelmioApiDocBundle#1586]
The web debug toolbar (wdt) component from symfony doesn't appear anymore.

The ajax call is not triggered, I got an error in console: `index.js:1 Uncaught (in promise) {}`

I think it's related to the new v3.5.0 version (not sure about this assertion)

my config:

```yaml
web_profiler:
    toolbar: true
    intercept_redirects: false
    excluded_ajax_paths: '^/((index|app(_[\w]+)?)\.php/)?_wdt'
```
