### ISSUE TITLE
How to generate API documentation in yaml swagger format?

### ISSUE THREAD

**Issue by supermiro** [nelmio/NelmioApiDocBundle#1613]
In Nelmio UI there is missing some yaml preview of generated API, is it possible to generate documentation in yaml format? Some tools for testing like soap ui are able to import yaml swagger file and then soap ui is able to work with this file and apis. Solution?

**Comment by hubertnnn** [comment]
If I remember correctly json as a subset of yaml, so if you need a yaml, then providing json should work fine.

**Comment by DEK-Pham-The-Anh** [comment]
In the latest version - nelmio_api_doc.yaml:
```
app.swagger_json:
    path: /api/doc.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_json }
app.yaml_yaml:
    path: /api/doc.yaml
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_yaml }
```
