### ISSUE TITLE
Models definition in yml file 

### ISSUE THREAD

**Issue by dasiekjs** [nelmio/NelmioApiDocBundle#1643]
Hello!
It is possible, to store all model definition in configuration file(yml, or external), to acces it in Property annotation? 

F.ex :
configuration
```
nelmio_api_doc:
    ...
    definitions:
        NelmioImageList:
            description: "Response for some queries"
            type: object
            properties:
                total:
                    type: integer
                    example: 42
```

And in Annotation

```
* @SWG\Response(
     *     response=200,
     *     description="Return information",
     *     @SWG\Schema(
     *         type="object",
     *         @SWG\Property(
     *              property="meta",
     *              type="object",
     *              @SWG\Property(
     *                  property="element",
     *                  description="Test Element",
     *                  type="object",
     *                  @Model(type="#/definitions/NelmioImageList")
     *              )
     *         )
     *     )
     * )
```

In application we can't use class annotation, but I wanted to make "reusable" definition, and I can't find any method for do this.
