### ISSUE TITLE
YAML-only OpenAPI setup

### ISSUE THREAD

**Issue by forsetius** [nelmio/NelmioApiDocBundle#1654]
I'd like to use only YAML files as a source of OpenAPI documentation and expose the `/api/doc` endpoint to serve it nicely rendered. Is i possible?
I can see in documentation that it's possible to setup global configuration in `nelmio_api_doc.documentation`. But how could I reference top-level openapi.yaml that references various route-specific OpenAPI YAML files? Or perhaps should I copy content of openapi.yaml into `nelmio_api_doc.documentation` and use `$ref`s to point to that route specific files?
I'd be grateful for advice.

**Comment by GuilhemN** [comment]
If you want to use a `$ref`, you can probably use a config similar to the one described in https://github.com/nelmio/NelmioApiDocBundle/issues/1655.

If you prefer having your config included directly in the resulting docs, you can register a new service:
```yaml
services:
    custom_api:
        class: Nelmio\ApiDocBundle\Describer\ExternalDocDescriber
        arguments: 
            - !service { class: stdClass, factory: file_get_contents, arguments: ['%kernel.project_dir%/pathtoyourdoc'] }
        tags: [ nelmio_api_doc.describer ]
```
