### ISSUE TITLE
[4.0.0-BETA1] $ref not supports external files

### ISSUE THREAD

**Issue by vertisan** [nelmio/NelmioApiDocBundle#1655]
Hi,  
I have tried to split my `nelmio_api_doc.yaml` into sub-files by use `$ref` and ability to load components, paths, etc. from external files: https://swagger.io/docs/specification/using-ref/#allowed-places  but it seems, this bundle not support this?  
Example:  
**nelmio_api_doc.yaml**
```yaml
nelmio_api_doc:
    documentation:
        paths:
            /api/v1/auth:
                $ref: './auth_controller.yaml'
```
**auth_controller.yaml**
```yaml
get:
  summary: Checks if user is authenticated
  tags:
    - Authentication
  security:
    - Basic
    - Bearer
```
but nothing happens, only endpoint `/api/v1/auth` going into `default`.
