### ISSUE TITLE
[Proposition] Support for many files with documentation.

### ISSUE THREAD

**Issue by vertisan** [nelmio/NelmioApiDocBundle#1666]
Hi,  
Are you planning to add support for many YAML files with documentation definitions? At this moment we can only use `imports` from Yaml but it's works as "rewrite" not "combine", e.g.
**documentation/part_1.yaml**
```yaml
nelmio_api_doc:
  documentation:
    components:
      schemas:
        Error:
          type: object
          properties:
            code:
              type: integer
            message:
              type: string
```  
**documentation/part_2.yaml**
```yaml
nelmio_api_doc:
  documentation:
    components:
      schemas:
        AnotherError:
          type: object
          properties:
            code:
              type: integer
            message:
              type: string
```
**nelmio_api_doc.yaml**
```yaml
imports:
  - { resource: 'documentation/part_1.yaml' }
  - { resource: 'documentation/part_2.yaml' }
```
Will generate only **part_2.yaml**, **part_1.yaml** will be overwrited.  
API Platform has support for it by `mapping` option:  
```yaml
api_platform:
    mapping:
        paths:
            - '%kernel.project_dir%/src/Entity'
            - '%kernel.project_dir%/config/api_platform/resources'
```
And in `resources/` I can create many as I want files with definitions.
