### ISSUE TITLE
NelmioApiDoc Bundle only using annotation routes

### ISSUE THREAD

**Issue by TheFox** [nelmio/NelmioApiDocBundle#1686]
I'm using Symfony 4.4. When I disable the Annotation routes in `config/routes/annotations.yaml` NelmioApiDoc Bundle does not show any documentation at all. Only when I define the Annotation routes. How can I setup NelmioApiDoc Bundle to also use the routes from the yaml file? When I run `./bin/console debug:router` I see all the routes.

**Comment by GuilhemN** [comment]
Sorry I am not able to reproduce your issue, are your `path_patterns` under `packages/nelmio_api_doc.yaml` correctly configured?

**Comment by TheFox** [comment]
I'm using the same config for another project, which is working as it should:

```yaml
nelmio_api_doc:
    documentation:
        info:
            title: '%app_name%'
            version: '%app_version%'
    areas: # to filter documented areas
        path_patterns:
            - ^/v1
```

It only works if I'm using `@Symfony\Component\Routing\Annotation\Route(name="xyz", path="/v1/hi")` in the function Annotation.

**Comment by GuilhemN** [comment]
I honestly see no reason this would happen, I suppose this is a configuration issue on your side.
Could you provide a reproducer?

**Comment by TheFox** [comment]
This is `nelmio/api-doc-bundle v3.5.0`. Also using `friendsofsymfony/rest-bundle 2.8.2`.

When I use just `- /` instead of `- ^/v1` in the `path_patterns` array to match all routes (or remove `areas` from the config) it shows the dev routes from Symfony as well as the Sonata Admin routes, and so on. But not my route.

In my Symfony 4.4 project I have this setup:

Routes file: `my_project/config/routes/my_project.yaml`
Content:
```yaml
my_project_api_v1_main:
    resource: "@MyProjectBundle/Resources/config/routing/api_v1.yaml"
    host: '%api_domain%'
    prefix: /v1
    type: rest
```

Bundle Routes file: `my_project/src/MyProjectBundle/Resources/config/routing/api_v1.yaml`
Content:
```yaml
# Test
my_project_api_v1_test:
    path: /test
    methods: GET
    defaults:
        _controller: MyProjectBundle:DefaultApi:test
```

Debug router `./bin/console debug:router` shows me the route: `my_project_api_v1_test                       GET        ANY      api.myproject.localhost   /v1/test.{_format}`

When I run Postman against http://api.myproject.localhost/v1/test.json it works as expected.

I'm not really sure what else I can configure. I copied the files from another project into this new project. In the old project it works as expected. But something must be different.

**Comment by TheFox** [comment]
@GuilhemN When I use

```yaml
# Test
my_project_api_v1_test:
    path: /test
    methods: GET
    controller: 'MyProjectBundle\Controller\DefaultApiController::testAction'
```

instead of

```yaml
# Test
my_project_api_v1_test:
    path: /test
    methods: GET
    defaults:
        _controller: MyProjectBundle:DefaultApi:test
```

it shows me the Route in the Nelmio Doc.

In [Util/ControllerReflector.php#L102](https://github.com/nelmio/NelmioApiDocBundle/blob/69df4c38b5d3839992269549df122b1d6b8affc0/Util/ControllerReflector.php#L102) the call $this->container->has($controller) returns false for `MyProjectBundle:DefaultApi`.

In `services.yaml` there is nothing special defined for autowiring the Controllers. It's the default which comes with the Symfony installation.
