### ISSUE TITLE
[4.0] Parameters defined in nelmio_api_doc required issue

### ISSUE THREAD

**Issue by charliefancelli** [nelmio/NelmioApiDocBundle#1690]
Hi,

If we set 
```
         parameters:
                version:
                    name: version
                    in: path
                    description: Api version
                    required: true
                    schema:
                        type: string
                        default: "1"
                        enum:
                            - "1"
```
in the `nelmio_api_doc.yaml` and we try to use it in Controller Annotation like 

```
@Nelmio\Operation(
     *     tags={"Test"},
     *     summary="Liste de test.",
     *     @OA\Parameter(
     *         ref="#/components/parameters/version"
     *     ),
```

We have an issues in the web interface, the execution is blocked 
![Capture d’écran 2020-07-27 à 17 39 27](https://user-images.githubusercontent.com/800399/88562929-9f21f880-d031-11ea-9e0b-e2dbf02b58ca.png)

Regards,

**Comment by GuilhemN** [comment]
Hi,

Sorry, I am not able to reproduce your issue.

Is there no error logged in your browser console? Does your operation have a response defined?

**Comment by charliefancelli** [comment]
You need to add two routes that used the parameter. The first one is working but the second not. 

I will try to make a sample next week, it will be easiest.

**Comment by jonhuteau** [comment]
Hi,

I'm getting this error as well and maybe I can bring some debug steps to reproduce the issue.

I have a controller action defined with `@Route("/{brand}/form/contact", methods={"POST"}, name="create_contact_form")`. Here, `{brand}` parameter is the causing me some troubles.

If I define a parameter annotation like this

```
     * @OA\Post(
     *     @OA\Parameter(
     *         name="brand",
     *         in="path",
     *         required=true,
     *         @OA\Schema(type="string", enum={"foo", "bar", "baz"})
     *     ),
     *    ...
     * )
```

<details>
<summary>Everything works just fine</summary>

![image](https://user-images.githubusercontent.com/58468627/97025823-ddf41b80-1558-11eb-91c9-64e560728fe4.png)

</details>

But now, if I use its component definition with ref

```
@OA\Parameter(ref="#/components/parameters/Brand")
```
```yaml
nelmio_api_doc:
  documentation:
    components:
      parameters:
        Brand:
          in: path
          name: brand
          required: true
          schema:
            type: string
            enum:
              - foo
              - bar
              - baz
          example: foo
```

I get the same issue as @charliefancelli.

My guess is that `@Route` annotation creates a definition for `brand`, which is merged when I declare another definition with `@OA\Parameter`.
But if the `@OA\Parameter` is a ref, both definition aren't merged, which gives

![image](https://user-images.githubusercontent.com/58468627/97026510-c4070880-1559-11eb-8e06-ad7dec8d5348.png)

I hope it can help
