### ISSUE TITLE
[4.0-beta] Server variable issue

### ISSUE THREAD

**Issue by charliefancelli** [nelmio/NelmioApiDocBundle#1691]
Hi,

When we try to add server variable like in the specification (https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#server-object)

```
nelmio_api_doc:
    documentation:
        servers:
          - url: https://api.example.com/secured/{version}
            description: API over HTTPS
            variables:
                version:
                    default: v1
```
in `nelmio_api.doc.yaml`, this error occured `User Notice: @OA\Server()->variables is an object literal, use nested @OA\ServerVariable() annotation(s) in \Nelmio\ApiDocBundle\ApiDocGenerator->generate() in /srv/vendor/nelmio/api-doc-bundle/ApiDocGenerator.php on line 82`

Do you have an idea where how we can fix it ?
Regards,
