### ISSUE TITLE
Empty security array is rendered into all operations

### ISSUE THREAD

**Issue by derrabus** [nelmio/NelmioApiDocBundle#1695]
### Problem

I'm using NelmioApiDocBundle 4.0.0-beta1 in a Symfony 4.4 application. My API is using the same authentication method for all endpoints, so I've configured authentication globally for the whole API as described in https://swagger.io/docs/specification/authentication/

```yaml
nelmio_api_doc:
    documentation:
        components:
            securitySchemes:
                SymfonySession:
                    type: apiKey
                    in: cookie
                    name: '%app.session_cookie_name%'
        security:
            - SymfonySession: []
```

This should do the trick. However, in the generated output, all operations receive an empty `security` array:

```JSON
"\/my\/endpoint": {
    "get": {
        "security":[]
    }
}
```

This defeats my global setting which is very unfortunate. I could add an annotation `@Security(name="SymfonySession")` to all of my endpoints. However, this method adds a lot of boilerplate and is error-prone since that annotation is easily forgotten when adding a new controller to the API.

### Suggestion
* Don't render `security` inside an operation unless security has explicitly been configured for that operation.
* Offer an easy way to force `security: []` on a specific operation.
