### ISSUE TITLE
routes does not work when we use php config files instead of yaml for routes in Symfony

### ISSUE THREAD

**Issue by Dattaraj-Devne** [nelmio/NelmioApiDocBundle#1698]
We need to use php configs instead of yaml in our Symfony project. So below yaml code is converted to php config file. But it does not work.

**YAML config**
```
app.swagger:
    path: /api/doc.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger }
```

**PHP config**
```    
$routes->add('app.swagger', '/api/doc.json')
        ->controller('nelmio_api_doc.controller.swagger')
        ->methods(['GET']);
```

Above php config in routes.php throws an symfony exception for Type Error.

```Argument 1 passed to Nelmio\ApiDocBundle\Util\ControllerReflector::getReflectionMethod() must be of the type string, array given, called in vendor/nelmio/api-doc-bundle/Describer/SwaggerPhpDescriber.php on line 232```

composer looks like below:
```
"symfony/framework-bundle": "^5.1.3",
"nelmio/api-doc-bundle": "^3.6"
```
