### ISSUE TITLE
[4.0] "Try out" possible without filling required parameters

### ISSUE THREAD

**Issue by NicoHaase** [nelmio/NelmioApiDocBundle#1705]
Using v4.0.0-BETA2, it is possible to submit a "Try out" request while a required field is not filled. The "Loading" animation spins and spins:

![Bildschirmfoto von 2020-08-21 15-30-11](https://user-images.githubusercontent.com/1069028/90896116-67556900-e3c3-11ea-9012-8a7bbcf11a5b.png)

The error console provides information about this:

> Error: Required parameter myself is not provided
>     cr index.js:4100
>     cr index.js:4070
>     Ne actions.js:416
>     ae utils.js:195
>     O Redux
>     c wrap-actions.js:33
>     r system.js:174
>     z system.js:461
>     Re actions.js:459
>     ae utils.js:195
>     O Redux
>     g spec-wrap-actions.js:9
>     r system.js:174
>     z system.js:461
>     n execute.jsx:24
>     React 14
> system.js:464:16

I had expected that the "Execute" button is disabled until all required fields are filled, or that some kind of warning pops up when clicking the button

**Comment by MelingRu** [comment]
Annotation
```php
     * @OA\Get(
     *     path="/user/{id}",
     *     summary="Retrieve User",
     *     description="Retrieve User",
     *     tags={"User"},
     *     @OA\Parameter(ref="#/components/parameters/Identifier"),
     *     @OA\Response(
     *          response="200",
     *          description="User Entity",
     *          @OA\JsonContent(ref=@Model(type=User::class, groups={"userForm"})),
     *     )
     * )
```
Config
```yaml
nelmio_api_doc:
    documentation:
        components:
            parameters:
                Identifier:
                    name: id
                    in: path
                    description: Entity Identifier
                    schema:
                        type: integer
                        pattern: \d+
```

Result
```json
{
    "/user/{id}": {
        "get": {
            "tags": [
                "User"
            ],
            "summary": "Retrieve User",
            "description": "Retrieve User",
            "operationId": null,
            "parameters": [
                {
                    "$ref": "#/components/parameters/Identifier"
                },
                {
                    "name": "id",
                    "in": "path",
                    "required": true,
                    "schema": {
                        "type": "string"
                    }
                }
            ],
            "responses": {
                "200": {
                    "description": "User Entity",
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/User"
                            }
                        }
                    }
                },
            }
        }
    }
}
```

In result identifier was added twice, as referenced parameter and as default parameter (string)

When i click "Try it out", fill id and "Execute", i get error in field "Required field is not provided"
