### ISSUE TITLE
[4.0] Cannot apply custom SecurityScheme to a route

### ISSUE THREAD

**Issue by hubertnnn** [nelmio/NelmioApiDocBundle#1725]
When I try to apply a custom security scheme to a single route I get an error:
```
Using the annotation "OpenApi\Annotations\SecurityScheme" as a root annotation in "App\Controller\TestController::apiTest()" is not allowed.
```

Steps to reproduce:
-------------------------

1. Create a custom security scheme:
```YAML
// config/packages/nelmio_api_doc.yaml
nelmio_api_doc:
  documentation:
    components:
      securitySchemes:
        Bearer:
          type: http
          scheme: bearer
          bearerFormat: JWT
```

2. Apply it to a route:
```PHP
    /**
     * @Route("/api/app/test", methods={"GET"})
     *
     * @OA\Tag(name="Test")
     * @OA\SecurityScheme(ref="#/components/securitySchemes/Bearer")
     */
    public function apiTest(Request $request)
    {
        return new Response('ok');
    }
```

Expected result:
---------------------
A padlock appearing next to a route indicating that authorization is required.
