### ISSUE TITLE
Bundle is adding path parameters if they are already added via reference

### ISSUE THREAD

**Issue by hubertnnn** [nelmio/NelmioApiDocBundle#1739]
If I add a path parameter using a reference eg `@OA\Parameter(ref="#/components/parameters/uuid")`
Defined in yaml as:
```
nelmio_api_doc:
  documentation:
    components:
      parameters:
        uuid:
          in: path
          name: id
          schema:
            type: string
          required: true
          description: "uuid"
          example: "00000000-0000-0000-0000-000000000000"
```

Then the resulting swagger file will have the parameter duplicated making it impossible to send a request from swagger-ui:
```
{
    "spec":{
        "openapi":"3.0.0",
        "info":{
            "title":"POS API doc",
            "description":"This is documentation for POS API",
            "version":"1.0.0"
        },
        "paths":{
            "/api/app/products/{id}/related":{
                "get":{
                    "tags":[
                        "Products"
                    ],
                    "operationId":null,
                    "parameters":[
                        {
                            "$ref":"#/components/parameters/uuid"
                        },
                        {
                            "name":"id",
                            "in":"path",
                            "required":true,
                            "schema":{
                                "type":"string"
                            }
                        }
                    ],
                    "responses":{
                        "200":{
                            "description":"Ok"
                        }
                    }
                }
            }
        },
        "components":{
            "parameters":{
                "uuid":{
                    "name":"id",
                    "in":"path",
                    "description":"uuid",
                    "required":true,
                    "schema":{
                        "type":"string"
                    },
                    "example":"00000000-0000-0000-0000-000000000000"
                }
            }
        }
    }
}
```

Bundle should not be adding default path parameters if said parameter is already defined.
