### ISSUE TITLE
Enum parameter invalid

### ISSUE THREAD

**Issue by Grandnainconnu** [nelmio/NelmioApiDocBundle#1749]
Hello,

There is a problem with my locale parameter, following:
```
nelmio_api_doc:
    documentation:
        components:
            parameters:
                locale:
                    name: _locale
                    in: path
                    description: 'Language'
                    required: true
                    schema:
                        type: string
                        enum: '%app.translator.fallbacks%'
                        default: '%app.translator.default_locale%'
```

With services parameters:
```
app.translator.default_locale: fr_FR
app.translator.fallbacks:
        - fr_FR
        - en_EN
        - es_ES
```

And in my routes included like this:
```
@OA\Parameter(ref="#/components/parameters/locale")
```

Everything is displayed correctly like this:
![image](https://user-images.githubusercontent.com/4025637/100409387-4ffed980-309e-11eb-88f4-7bd97d33a5f5.png)
![image](https://user-images.githubusercontent.com/4025637/100409416-5d1bc880-309e-11eb-8079-208264c4c4e8.png)

But when I execute the request I get invalid parameter, with any language it's always like this:
![image](https://user-images.githubusercontent.com/4025637/100409447-6efd6b80-309e-11eb-983a-72a4ce938884.png)

Somebody already had such problem?
Thanks in advance!
