### ISSUE TITLE
[v4.0] Possibility to render multiple filtered areas

### ISSUE THREAD

**Issue by andre-tronin** [nelmio/NelmioApiDocBundle#1754]
Users of our API get access only for some routes, which have been unlocked for that user.
For example:
User1 can use Route1 and Route3
User2 can use Route2 and Route3
It can be changed later, so the list of visible areas must be dynamic.
If the user can actually use the route, there is an authorization. So the problem is only the visibility of areas documentation for the user.
For the v3 we had build a workaround:
```php
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\DependencyInjection\ServiceLocator;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Security\Core\Security;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/customer/docs", name="app_customer_api-docs", methods={"GET"})
 */
class SwaggerUiController extends AbstractController
{
    private ApiDocGeneratorFacade $apiDocGeneratorFacade;
    private Security $security;

    public function __construct(ApiDocGeneratorFacade $apiDocGeneratorFacade, Security $security)
    {
        $this->apiDocGeneratorFacade = $apiDocGeneratorFacade;
        $this->security = $security;
    }

    public function __invoke(): Response
    {
        return $this->render(
            '@NelmioApiDoc/SwaggerUi/index.html.twig',
            ['swagger_data' => ['spec' => $this->apiDocGeneratorFacade->generate($this->security->getUser())]]
        );
    }
}

class ApiDocGeneratorFacade
{
    private ServiceLocator $apiDocGeneratorLocator;

    public function __construct(ServiceLocator $apiDocGeneratorLocator)
    {
        $this->apiDocGeneratorLocator = $apiDocGeneratorLocator;
    }

    public function generate(User $apiUser): array
    {
        $areas = Areas::getAreasByApiUser($apiUser);

        $apiDocGenerators = array_map(fn (string $area) => $this->apiDocGeneratorLocator->get($area), $areas);

        $specs = [];
        foreach ($apiDocGenerators as $apiDocGenerator) {
            $specs = array_replace_recursive($specs, json_decode($apiDocGenerator->generate()->toJson(), true));
        }

        return $specs;
    }
}
```
nelmio_api_doc.yml:
```yaml
nelmio_api_doc:
    documentation:
        info:
            title: api
            description: api
            version: 2.2.2
        components:
            securitySchemes:
                Basic:
                    type: http
                    scheme: basic
                Bearer:
                    type: apiKey
                    name: Authorization
                    in: header
    areas:
        default:
            path_patterns:
                - '^/api'
        area_1:
            name_patterns:
               - '^route_1'
        area_2:
            name_patterns:
               - '^route_2'
        area_3:
            name_patterns:
               - '^route_3'
```
But with update to v4 it stopped to work:
`
User Notice: $ref "#/components/schemas/SomeModel" not found for @OA\Items() in \App\Domain\Model\SomeModelCollection->getItems in /path/src/Domain/Model/SomeModelCollection.php
`
This error occurs in the case when two or more areas, that has to be shown uses same `@Model` somewhere.
If there are no such areas, the workaround works as expected.

What should we change, that the workaround always works?
Or perhaps there is another solution for our needs that we did not discover jet?
