### ISSUE TITLE
How to use constants in Yaml?

### ISSUE THREAD

**Issue by cprn** [nelmio/NelmioApiDocBundle#1800]
OpenApi [documentation](https://github.com/zircote/swagger-php/blob/master/docs/Getting-started.md#using-variables) states the following:
> You can use constants inside doctrine annotations.
> ```php
> define("API_HOST", ($env === "production") ? "example.com" : "localhost");
> ```
> ```php
> /**
>  * @OA\Server(url=API_HOST)
>  */
> ```
> 
> When you're using the CLI you'll need to include the php file with the constants using the `--bootstrap` options:
> ```sh
> openapi --bootstrap constants.php
> ```
But how do I pass `--bootstrap` argument to NelmioApiDocBundle so I could use constants in `config/packages/nelmio_api_doc.yaml`?

Ideally I'd like class constants to resolve in the following scenario:
```yml
examples:
    - summary: ex1
      value: { code: SomeClass::code1, message: OtherClass::message1 }
    - summary: ex2
      value: { code: SomeClass::code2, message: OtherClass::message2 }
```

I know nelmio/alice can resolve `<(SomeClass::code1)>` - can this be somehow used in NelmioApiDocBundle?
