### ISSUE TITLE
additionalProperties: <bool> in nelmio_api_doc.yml gets translated into array instead of boolean value in output

### ISSUE THREAD

**Issue by benkelukas** [nelmio/NelmioApiDocBundle#1806]
Hi, 
thanks for the awesome bundle! I'm having one issue with the `additionalProperties` that I want to use in my definitions in YML files - e.g. `nelmio_api_doc.yml` config file or other `YML` files loaded as external docs.

The issue is, that if I define for example `additionalProperties: false` in one of my schemas in `nelmio_api_doc.yml` it is represented as `additionalProperties: { }` instead of `additionalProperties: false` in the generated `YML` file, e.g. after running `bin/console nelmio:apidoc:dump` command.

Example schema:

```yml
SomeSchema:
    type: object
    properties:
        foo:
            type: string
        bar:
            type: integer
    required:
        - foo
        - bar
    additionalProperties: false
```

Example YML generated after running `bin/console nelmio:apidoc:dump` 

```yml
SomeSchema:
  required:
    - device
  properties:
        foo:
            type: string
        bar:
            type: integer
    required:
        - foo
        - bar
    additionalProperties: { }
```

I'm using `nelmio/api-doc-bundle` in version `4.2.0`

I've traced this behaviour to `vendor/cebe/php-openapi/src/spec/Schema.php:137`, the key `additionalProperties` already gets into this method as an `array` instead of `boolean` but I was not able to find out from where it got there.

I've created a minimal reproducible example - https://github.com/benkelukas/nelmio-api-doc-issue-example/tree/master/myapp

There is a schema in [myapp/config/packages/nelmio_api_doc.yml](https://github.com/benkelukas/nelmio-api-doc-issue-example/blob/master/myapp/config/packages/nelmio_api_doc.yaml) and you can see the generated output in [myapp/api_doc.json](https://github.com/benkelukas/nelmio-api-doc-issue-example/blob/master/myapp/api_doc.json)

You can run it locally by running `docker-compose up` and `docker-compose exec bin/console nelmio:apidoc:dump`

Any idea what might be happening?

Thanks
