### ISSUE TITLE
API versioning with FOSRest

### ISSUE THREAD

**Issue by zys-gd** [nelmio/NelmioApiDocBundle#1809]
Could someone explain how to versioning models in documentation?
I have FOSRest, JMS, NelmioApiDoc (v3). API versions of models (@Until, @Since) work good, but they dont displayed correctly in the documentation.

```
class SomeDTO
{
    /**
     * @var int
     *
     * @JMS\Type("integer")
     * @JMS\Until(version="2")
     */
    public $someField;

    /**
     * @var int
     *
     * @JMS\Type("integer")
     * @JMS\Since(version="3")
     */
    public $anotherField;
}
```
routing.yml:
```
api.v3.client:
    resource: 'routing.yml'
    prefix: /api/v3/client
    requirements:
        version: '3'
    defaults:
        version: 3
```

But in the Nelmio's documentation there not any versions switcher for displaying models.
