### ISSUE TITLE
[4.3] API doc Default Url is wrong behind a proxy (nelmio_api_doc.documentation.servers is ignored)

### ISSUE THREAD

**Issue by jeremy-rafflin** [nelmio/NelmioApiDocBundle#1831]
Hi, 
My API is behind a proxy who accept https (_https://www.monurls.com/api/doc_).
In my Swagger UI documentation url is _http://www.monurls.com/api/doc_ (the url in the Select under Servers). Th SSl is not detected because I am behind a proxy. 

Is it possible to use relative url in the swagger UI ?

Test:
I have configure :
```
nelmio_api_doc:
    documentation:
        servers:
            - url: https://www.monurls.com/api/doc
            - url: http://www.monurls.com/api/doc

```
But it's ignored.
I see in SwaggerUiController : 
```
if ('' !== $request->getBaseUrl()) {
    $spec->servers = [new Server(['url' => $request->getSchemeAndHttpHost().$request->getBaseUrl()])];
}
```
The config is ignored if '' !== $request->getBaseUrl(). Is it a error ?
