### ISSUE TITLE
Responses $refs empty (no example available)

### ISSUE THREAD

**Issue by shubaivanqbee** [nelmio/NelmioApiDocBundle#1859]
I use
            "name": "nelmio/api-doc-bundle",
            "version": "v4.3.0",
            
with  "symfony/framework-bundle": "5.3.3",            
            
And execute evrything like in documentation, added new schema and try to used in by ref

config/packages/nelmio_api_doc.yaml

```
nelmio_api_doc:
    documentation:
        components:          
            schemas:
                NelmioImageList:
                    description: "Response for some queries"
                    type: object
                    properties:
                        total:
                            type: integer
                            example: 42
```                            

and my action

```
     * @OA\Response(
     *     response=200,
     *     description="List of image definitions",
     *     @OA\JsonContent(@OA\Schema(
     *       type="object",
     *       title="ListOperationsResponse",
     *       additionalProperties={"$ref": "#/components/schemas/NelmioImageList"}
     *     ))
     * )
     * 
```

but I faced with no example available, could someone help?  

I executed 

php bin/console a:install
and totally cleared cache
rm -rf var/cache/ && php bin/console c:c && chmod 777 -R var/cache/

the same case when I use commom Operation annotation

    use Nelmio\ApiDocBundle\Annotation\Operation;
    use OpenApi\Annotations as OA;

     * @Operation(
     *     tags={"Stripe"},
     *     summary="test",
     *     @OA\RequestBody(
     *         request="body",
     *         description="test"
     *     ),
     *     @OA\Response(
     *         response=200,
     *         description="test",
     *         @OA\JsonContent(@OA\Schema(
     *              type="object",
     *              title="test",
     *              additionalProperties={"$ref": "#/components/schemas/NelmioImageList"}
     *        ))
     *     )
     * )
     
   

As you can see in screen in global Schema section models viewed correct, perhaps some problem with `ref` or ..

![image](https://user-images.githubusercontent.com/78418206/128864299-752a7351-cfb7-4ee4-b996-ee40556475e4.png)

the same case when I used

```
     * @Operation(
     *     tags={"Stripe"},
     *     summary="test",
     *     @OA\RequestBody(
     *         request="body",
     *         description="test"
     *     ),
     *     @OA\Response(
     *         response=200,
     *         description="test",
     *         @OA\JsonContent(@OA\Schema(
     *              type="object",
     *              example={"foo": "bar", "hello": "world"}
     *         ))
     *     )
     * )
```

looks like global problem with response model, but everything works correct and show corerct when I used Model annotation

```
     * @Operation(
     *     tags={"Stripe"},
     *     summary="test",
     *     @OA\RequestBody(
     *         request="body",
     *         description="test",
     *         required=true,
     *         @Model(
     *              type=MyRequest::class,
     *              groups={MyRequest::API_DOC}
     *         )
     *     ),
     *     @OA\Response(
     *         response=200,
     *         description="test",
     *         @Model(
     *              type=MyResponse::class,
     *              groups={MyResponse:API_DOC}
     *         )
     *     )
     * )
     * 
```

I updated to v4.4.0 but not helped, waht I'm doing wrong ?
