### ISSUE TITLE
Nelmio doesn't work with API Platform

### ISSUE THREAD

**Issue by agennari** [nelmio/NelmioApiDocBundle#1866]
Hello

I'm trying to integrate Nelmio with API Platform to write Swagger Decoration on my controllers.

Configuration : 
`"nelmio/api-doc-bundle": "^4.4",
"api-platform/core": "^2.6",`

In config/packages/api_platform.yaml:

```
api_platform:
    enable_swagger_ui: false
    enable_re_doc: false
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
        api_keys:
            apiKey:
                name: Authorization
                type: header
    enable_nelmio_api_doc: true
```

Example in controller:

```
<?php


namespace App\Controller;

use Nelmio\ApiDocBundle\Annotation\Operation;
use Nelmio\ApiDocBundle\Annotation\Security;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Attribute\AsController;
use Symfony\Component\Routing\Annotation\Route;
use Nelmio\ApiDocBundle\Annotation\Model;
use Nelmio\ApiDocBundle\Annotation\Security as OASecurity;
use OpenApi\Annotations as OA;

/**
 * Class testController
 * @package App\Controller
 */
class testController extends AbstractController
{
    /**
     * List the rewards of the specified user.
     *
     * This call takes into account all confirmed awards, but not pending or refused awards.
     *
     * @Route("/api/{user}/rewards", methods={"GET"})
     * @OA\Response(
     *     response=200,
     *     description="Returns the rewards of an user",
     *     @OA\JsonContent(
     *        type="array",
     *        @OA\Items(ref=@Model(type=Reward::class, groups={"full"}))
     *     )
     * )
     * @OA\Parameter(
     *     name="order",
     *     in="query",
     *     description="The field used to order rewards",
     *     @OA\Schema(type="string")
     * )
     * @OA\Tag(name="rewards")
     * @Security(name="Bearer")
     */
    public function test(Request $request): Response
    {
        dd('test');

        return new Response(json_encode($data), 200);
    }
}
```

But, In my swagger UI, doesn't have the doc updated with what I wrote on my controller...
I didn't find any documentation about integrate Nelmio with APIPlatform (with bult-in integration by nelmio)

Can someone help me?

Thanks
