### ISSUE TITLE
Should Route Requirements be Surround with `^...$` in Path Schema Patterns?

### ISSUE THREAD

**Issue by chrisguitarguy** [nelmio/NelmioApiDocBundle#1873]
Given a route like this:

```
    <route
        id="users.view"
        methods="GET"
        path="/users/{userId}"
        controller="App\Controller\UsersController::view">
            <requirement key="userId">[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}</requirement>
    </route>
```

an open API schema gets generated where the path parameter looks like this:

```yaml
parameters:
  -
    name: userId
    in: path
    required: true
    schema:
      type: string
      pattern: '[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}'
 ```

But the [pattern docs](https://swagger.io/docs/specification/data-models/data-types/#pattern) say that without `^` and `$` the pattern is a partial match, not a full string.

For a route, where the generated regex would require the specific, full string it might make sense to change the [route describer](https://github.com/nelmio/NelmioApiDocBundle/blob/b53edda10ce4a263991d6f10032a905f783b3d29/RouteDescriber/RouteMetadataDescriber.php#L60) to surround the requirement with `^...$`.

Here's the regex that symfony generates on that route, for context:

![Screen Shot 2021-09-14 at 10 58 10 AM](https://user-images.githubusercontent.com/1010392/133292541-487df4ee-1738-4b63-b350-89c4ff9707ba.png)

Thoughts?
