### ISSUE TITLE
Twig necessary for JSON-Output since 4.6

### ISSUE THREAD

**Issue by CatoTH** [nelmio/NelmioApiDocBundle#1874]
Hi,

starting version 4.6, it looks like twig, including symfony//asset is necessary to create the JSON output from the console.  
The is the error message that I get (when doing a cache:clear, in this case):
```
Script cache:clear returned with error code 1
!!
!!   // Clearing the cache for the prod environment with debug
!!   // false
!!
!!
!!  In CheckExceptionOnInvalidReferenceBehaviorPass.php line 86:
!!
!!    The service "nelmio_api_doc.render_docs.html" has a dependency on a non-exi
!!    stent service "twig".
!!
!!
!!  cache:clear [--no-warmup] [--no-optional-warmers]
!!
!!
Script @auto-scripts was called via post-update-cmd
```
It does work again if I restrict the version to 4.5.

**Comment by rwatt-futurenet** [comment]
You can fix this by making the service only load the JSON renderer by adding this to services.yaml;
```yaml
    nelmio_api_doc.render_docs:
        class: Nelmio\ApiDocBundle\Render\RenderOpenApi
        arguments:
            - "@nelmio_api_doc.generator_locator"
            - "@nelmio_api_doc.render_docs.json"
```

The first argument should always be generator_locator, the rest are the renderers you want to make available - the built in ones are `nelmio_api_doc.render_docs.html`, `nelmio_api_doc.render_docs.json` and `nelmio_api_doc.render_docs.yaml`. Only the html renderer needs twig.
