### ISSUE TITLE
Ability to add title/description to custom models

### ISSUE THREAD

**Issue by Seldaek** [nelmio/NelmioApiDocBundle#1894]
It'd be great if the model names feature (https://symfony.com/bundles/NelmioApiDocBundle/current/alternative_names.html) would let one customize the title and description of every model. Right now if you define several they all have the entity name as title and that's really unhelpful for the doc consumer.

What I mean in practice would be allowing this:

```
nelmio_api_doc:
    models:
        names:
            - { alias: MainUser,        type: App\Entity\User, name: "User (main)", description: "The main user object with all properties" }
            - { alias: MainUser_light,  type: App\Entity\User, groups: [light] }
            - { alias: MainUser_secret, type: App\Entity\User, areas: [private] }
            - { alias: MainUser,        type: App\Entity\User, groups: [standard], areas: [private] }
```

**Comment by GuilhemN** [comment]
Actually this should already be doable by doing the following:
```
nelmio_api_doc:
    documentation:
        schemas:
            components:
                MainUser: { title: "User (main)", description: The main user object with all properties }
    models:
        names:
            - alias: MainUser
              type: App\Entity\User
            - { alias: MainUser_light,  type: App\Entity\User, groups: [light] }
            - { alias: MainUser_secret, type: App\Entity\User, areas: [private] }
            - { alias: MainUser,        type: App\Entity\User, groups: [standard], areas: [private] }

```

would that be an acceptable solution for you?
