### ISSUE TITLE
How to use multiple YAML files ?

### ISSUE THREAD

**Issue by quentinlds** [nelmio/NelmioApiDocBundle#1930]
Hi,
I saw in #1654 that we can define our endpoints in a YAML file. 
But, there is a way to use mutiple yaml files ? 
Somethings like 
```
doc/user.yaml
doc/client.yaml
```
And define endpoints in all of them unstead of using one big documention.yaml ?

**Comment by akalineskou** [comment]
Have a look at areas https://symfony.com/bundles/NelmioApiDocBundle/current/areas.html

You can probably (havent tested it, but if using symfony it should merge them nicely) create a yaml for each area and override the documentation for each one (it needs the default area, you can set it to null or empty)

```yaml
nelmio_api_doc:
    areas:
        default:
            path_patterns: [ ^/api ]
            host_patterns: [ ^api\. ]
            documentation:
              - openapi: 3.0.0
                info: bla bla
```

```yaml
nelmio_api_doc:
    areas:
        internal:
            path_patterns: [ ^/internal ]
            documentation:
              - openapi: 3.0.0
                info: bla bla
```

```yaml
nelmio_api_doc:
    areas:
        commercial:
            path_patterns: [ ^/commercial ]
            documentation:
        store:
            # Includes routes with names containing 'store'
            name_patterns: [ store ]
            documentation:
```
