### ISSUE TITLE
Session cookie header parameter support

### ISSUE THREAD

**Issue by pavel-vasiluk** [nelmio/NelmioApiDocBundle#1951]
I have got some API-endpoints that are designed to be protected access via session-cookie. And as far as I understand, OpenAPI specification supports it, but I cannot really make it work via nelmio features.

1. I have added session cookie parameter to config:
```
        components:
            securitySchemes:
                Cookie:
                    type: apiKey
                    name: PHPSESSID
                    in: cookie
```

2. Authorization has been added to UI. I have added the Cookie.
![image](https://user-images.githubusercontent.com/30865120/149377251-4398dca6-fd64-41a5-a3d0-9a814c441218.png)

3. Then I proceed to endpoint scheme and press execute. And get redirected response (302, no active session). After debugging it. I see that `Cookie` header has been ignored to be set.
![image](https://user-images.githubusercontent.com/30865120/149378299-8f29195f-5b04-42a4-b4db-fe2697ccbabc.png)

4. However if I execute curl (shown in the screenshot above), I am able to get authorized content by provided session cookie.

Is it an expected behavior, or a known bug, or some design decision to not support session cookie parameter? 
As according to Swagger documentation, this feature is supported https://swagger.io/docs/specification/authentication/cookie-authentication/
