### ISSUE TITLE
#[PathParameter] could get parameter type from PHP argument type hint

### ISSUE THREAD

**Issue by mathroc** [nelmio/NelmioApiDocBundle#1980]
Hi!

I'm really glad `PathParameter` can now be used on constructor arguments (thx to https://github.com/nelmio/NelmioApiDocBundle/pull/1973)

It looks like, by default, it assume the parameter is a string even if the argument is typed otherwise, eg:

```php
public function myRoute(#[PathParameter] int $id) {}
```

this will generate:

```yaml
      parameters:
        -
          name: id
          in: path
          required: true
          schema:
            type: string
```

but it could be improved to generate a `type: integer` schema instead
