### ISSUE TITLE
Nelmio bundle generate duplicated data schema in openAPI doc

### ISSUE THREAD

**Issue by vikbert** [nelmio/NelmioApiDocBundle#1996]
State of my System:

- Symfony 5.4.5
- php 8.0.1
- NelmioApiDocBundle 4.8

after I opened the api doc via route "/api/doc", the schema of my data entities were displayed more than one time. Please see my screenshot.

<img width="1576" alt="MicrosoftTeams-image (2)" src="https://user-images.githubusercontent.com/3229226/168051665-943908d9-c3f3-4c35-9a18-203b5aa74a99.png">

How can I generate the data schema without repeating?

**Comment by GuilhemN** [comment]
Are you using `@Model` annotations with different groups / options?

At the time, for every set of options, a new schema is generated.

**Comment by chrisguitarguy** [comment]
What @GuilhemN said, I experience this quite a bit as well and work around it by creating model aliases in the config.

```yml
nelmio_api_doc:
  models:
    names:
      - alias: SettingExample
        type: App\SettingDto
        groups: ["default"]
 ```
