### ISSUE TITLE
Dynamic API version

### ISSUE THREAD

**Issue by sharifzadesina** [nelmio/NelmioApiDocBundle#1998]
Is it possible to have a dynamic version?
I want to change the `version` depending on the area name.

```yaml
nelmio_api_doc:
    documentation:
        info:
            title: My App
            description: This is an awesome app!
            version: 1.0.0
    areas: # to filter documented areas
        default: ~
        v1:
            path_patterns:
                - ^/api/v1(?!/doc$) # Accepts routes under /api/v1 except /api/v1/doc
```

**Comment by GuilhemN** [comment]
Sure, you can actually specify the documentation per area as following:
```yaml
nelmio_api_doc:
    documentation:
        info:
            title: My App
            description: This is an awesome app!
            version: 2.0.0
    areas: # to filter documented areas
        default: ~
        v1:
            documentation:
                info:
                    version: 1.0.0
            path_patterns:
                - ^/api/v1(?!/doc$) # Accepts routes under /api/v1 except /api/v1/doc
```

I thought it was described in the docs but apparently not... If you'd like to document this this would a very much appreciated first contribution :)
