### ISSUE TITLE
Multiple definitions for @OA\Post()->responses Using: Skipping:

### ISSUE THREAD

**Issue by MrBelbedair** [nelmio/NelmioApiDocBundle#2033]
Hey There!

we're using the Api with Annotations un our Controllers.

now symfony routes.yml or routes.php in our case provides the possibility to make host an array for example ['localhost', 'exampel.local'] this is done for our controllers.

The ApiDocBundle also provides the possibility for these routes but it does not work if we want to access the doc. if we just remove the 'exampel.local' and pass just the string 'localhost' we get the error "Multiple definitions for @OA\Post()->responses Using: Skipping:....." i assume because the annotations are loaded two times because of the multiple controller hosts?

**Comment by temposys** [comment]
I have similar problem
the same type of errors about "Multiple definitions for @OA\...."
i have localization with such config:
```
controllers:
    resource: ../../src/Controller/
    type: annotation
    prefix:
        en: '%project_prefix%'
        fr: '%project_prefix%/fr'
```
If I comment `prefix` block - no errors anymore.

Any solution for this case?
