### ISSUE TITLE
How to reuse an entire response shape using definitions and ref in 3.x?

### ISSUE THREAD

**Issue by gremo** [nelmio/NelmioApiDocBundle#2044]
I'm successfully reusing parameters with the following configuration, and it's a good thing when you have a lot of parameters with same name and type:

```yaml
nelmio_api_doc:
    parameters:
        ParamDescriptionContains:
            in: query, 
            name: 'description[contains]',
            type: string, 
            description: Filtro descrizione (contiene). 
```

In my controller action:

```php
/**
 * List all zones.
 *
 * @Rest\Get(name="_api_zone_get_all")
 * @Rest\View()
 *
 * @SWG\Tag(name="Zone")
 * @SWG\Parameter(ref="#/parameters/ParamDescriptionContains")),
 * @SWG\Response(
 *     response=Response::HTTP_OK,
 *     description="In case of success.",
 *     @SWG\Schema(type="array", @SWG\Items(ref=@Nelmio\Model(type=Zone::class))),
 * )
 */
public function getAllAction(Request $request)
{
}
```

I'd like to do the same with the response, avoid repeating the code and description all the time:

```yaml
nelmio_api_doc:
        responses:
            ResponseOk:
                response: 200
                description: In case of success
```

But it won't work:

```php
/**
 * List all zones.
 *
 * @Rest\Get(name="_api_zone_get_all")
 * @Rest\View()
 *
 * @SWG\Tag(name="Zone")
 * @SWG\Parameter(ref="#/parameters/ParamDescriptionContains")),
 * @SWG\Response(
 *     ref="#/responses/ResponseOk"),
 *     @SWG\Schema(type="array", @SWG\Items(ref=@Nelmio\Model(type=Zone::class))),
 * )
 */
public function getAllAction(Request $request)
{
}
```

> Using the annotation "Swagger\\Annotations\\Schema" as a root annotation in "App\\Controller\\API\\ZoneController::getAllAction()" is not allowed. It should probably be nested in a `@SWG\\Response` or `@SWG\\Parameter` annotation.

**Comment by GuilhemN** [comment]
Hmm not sure how your first example works, you should be using:
```yaml
nelmio_api_doc:
  documentation:
    parameters:
        ParamDescriptionContains:
            in: query, 
            name: 'description[contains]',
            type: string, 
            description: Filtro descrizione (contiene). 
```

Similarly, responses should be put under `nelmio_api_doc.documentation.responses`.

About the error you obtain, your usage looks correct on the method. But are you adding a `@Schema` annotation to your controller class definition?
If that's the case we should probably make this error clearer, `@Schema` is not supported on controllers class.
