### ISSUE TITLE
Property "App\Model\Custom\Modules::globalScopes" is an array, but its items type isn't specified. You can specify that by using the type `string[]` for instance or `@OA\Property(type="array", @OA\Items(type="string"))`.

### ISSUE THREAD

**Issue by gfriessner** [nelmio/NelmioApiDocBundle#2058]
My src/Model/Custom/Modules.php

The extends Model class has golbalScope.

```
<?php

namespace App\Model\Miggroup;

use Illuminate\Database\Eloquent\Model;

class Modules extends Model
{
}

```

my nelmio...yml:

```
  areas: # to filter documented areas
    default:
      disable_default_routes: true
      documentation:
        tags:
          - name: "default"
      path_patterns:
        - ^/(?!/doc$) 
    internal:
      documentation:
        tags:
          - name: "Tag1"
      path_patterns:
        - ^/modules(?!/doc$) 
```        

How can I avoid to disable to parse namespaces or the folder `src/Model`in Nelmio?

It would be great that the documentation might get an update.
