### ISSUE TITLE
Larger data crashing the browser

### ISSUE THREAD

**Issue by igordeveloper** [nelmio/NelmioApiDocBundle#2063]
I'm using the api-doc-bundle 4.10.2  with larger swagger data generated in Symfony, but when I access the api doc and I try expand 2 or more operations the browser is crash.

Follow my configuration:
```
nelmio_api_doc:
    areas:
        path_patterns: # an array of regexps
        - ^/[a-z]
    documentation:
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
```

Is there a way to paginate the api doc?

Thank you.
