### ISSUE TITLE
Symfony 6.3 - Areas path patterns are not working

### ISSUE THREAD

**Issue by JulienSellier** [nelmio/NelmioApiDocBundle#2122]
Hello,

I am upgrading my app to Symfony 6.3 (from Symfony 4.4) ; I didn't changed the Nelmio API Doc version (4.11.1) but my area configuration is not working after the upgrade... 

```yaml
nelmio_api_doc:
    documentation:
        info:
            title: Test
            description: ~
            version: 1.0.0
    areas: # to filter documented areas
        default:
            disable_default_routes: true
        test:
            path_patterns:
                - ^/test
```

config/routes/nelmio_api_doc.yaml
```yaml
app.swagger:
    path: /doc/{area}.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger, area: default }

app.swagger_ui:
    path: /doc/{area}
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui, area: default }
```

When I access to /doc/test, I should only see API routes starting with "/test" and it's not the case, I see all the API platform auto generated routes.

I figured out that the function \Nelmio\ApiDocBundle\Routing\FilteredRouteCollectionBuilder::filter works well because it only returns the /test routes but then I don't know what happen and all API routes are displayed.

Maybe I missed something in Symfony configuration which is needed to make this configuration to work ? Can you help me ?

Thanks!
