### ISSUE TITLE
Allow `custom Processors` for `swagger-php`

### ISSUE THREAD

**Issue by Luehrsen** [nelmio/NelmioApiDocBundle#2146]
There are several issues that require somewhat custom behavior, mostly for convenience in managing huge codebases. A lot of those would be solved with the option of a custom processor. (see #1871, #1721)

Currently, there is no way to register custom processors in the `NelmioApiDocBundle`. It would be nice to be able to hook into the `setProcessors` function somewhere here: https://github.com/nelmio/NelmioApiDocBundle/blob/bd10c342bfe7aae3efe864be2708cd93b01da641/ApiDocGenerator.php#L87-L92

Ideally we could register own processors through the `nelmio_api_doc.yaml` config file:
```yaml
# config/packages/nelmio_api_doc.yaml
nelmio_api_doc:
    areas:
    documentation:
    processors:
      - /App/OpenApi/Processors/CustomProcessor1
      - /App/OpenApi/Processors/CustomProcessor2
```

For code quality and clarity I would suggest enforcing these processors to implement `ProcessorInterface`.

**Comment by Nyholm** [comment]
I would also love to see this feature. 

Are you open for PRs?

**Comment by Luehrsen** [comment]
> I would also love to see this feature.
> 
> Are you open for PRs?

Theoretically yes. But I've never developed within symfony packages. So I would certainly need some guidance. 

I'll open a PR and slap together a POC, and then maybe we can clean it up with the help of some feedback! :D

**Comment by Nyholm** [comment]
Sure, <3

If you are super fancy, then you can make it configurable with configuration. But the easier solution is to just work with "tagged service" in dependency injection. 

Ie the user writes something like: 

```yaml
services:
  App\OpenApi\Processors\CustomProcessor:
    tags: [ 'swagger.processor', before: 'OpenApi\Processors\DocBlockDescriptions' ]
```

With a CompilerPass you may be to add this compiler to the `Generator` service.
