### ISSUE TITLE
OpenAPI Specification Extensions

### ISSUE THREAD

**Issue by andersonpem** [nelmio/NelmioApiDocBundle#2224]
How can I use OpenAPI Specification Extensions to this bundle?

According to OpenAPI specification, any extra parameter has to start with x-*. Also, field names beginning x-oai- and x-oas- are reserved :) 

Imagine I have the following code:
```yaml
nelmio_api_doc:
    documentation:
        servers:
            - url: '%env(DOCUMENTATION_URL)%'
        info:
            title: Some sample API
            description: Totally realistic API
            version: 1.0.0
            x-build: '#SomeCommitHash'
```

I can't make the x-build be rendered in the outputted JSON. Do I need to enable some option?

I'm using v4.20 on Symfony 6.4

Thank you and sorry if this is a stupid question :)
