### ISSUE TITLE
Make the default area accessible at /doc.json

### ISSUE THREAD

**Issue by JorickPepin** [nelmio/NelmioApiDocBundle#2227]
Having the following configuration, I can access the default area at `/doc` (as well as `/doc/default`), but I get a 404 error at `/doc.json`. I have to go to `/doc/default.json` to get it. Is this configurable? Thanks.

```yaml
app.swagger_json:
    path: /doc/{area}.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_json, area: default }

app.swagger_ui:
   path: /doc/{area}
   methods: GET
   defaults: { _controller: nelmio_api_doc.controller.swagger_ui, area: default }
```
