### ISSUE TITLE
@OA\Items() is required when @OA\Property

### ISSUE THREAD

**Issue by maxence-futures** [nelmio/NelmioApiDocBundle#2240]
I got this error after installation, without any documentation wrote in api.
Route file is ok,
security file is ok.

`User Warning: @OA\Items() is required when @OA\Property(property="translations") has type "array" in`

**Comment by DjordyKoert** [comment]
As the message suggest, you need to add a `@OA\Items()` for your `translations` property.
```php
 * @OA\Property(
 *      property="translations"
 *      type="array",
 *      @OA\Items()
 * )
```

**Comment by DjordyKoert** [comment]
Do you have some more context? 

- Bundle version
- Config used
- Do you use Symfony's `Map*` attributes? https://symfony.com/bundles/NelmioApiDocBundle/current/symfony_attributes.html

This warning is thrown inside the underlying swagger-php:
https://github.com/zircote/swagger-php/blob/038da8ad219f1e9c3f82c5d84c47da3b6f35039c/src/Annotations/Schema.php#L488

**Comment by maxence-futures** [comment]
- bundle version : ```"nelmio/api-doc-bundle": "^4.23"```
- config : 
```
    areas: # to filter documented areas
        path_patterns:
            - ^/v1/. # Accepts routes under /v1 except /v1/doc
        disable_default_routes: true
```
- And yes we are using Symfony's attributes. 

This warning came after installation and initialization of nelmio bundle, no more.
