### ISSUE TITLE
Duplication of query parameter if it's a reference

### ISSUE THREAD

**Issue by jneidel** [nelmio/NelmioApiDocBundle#2314]
### Version

4.28.0

### Description

Referencing a parameter defined in components duplicates the parameter in the rendered output.

<img width="523" alt="Screenshot 2024-07-15 at 12 38 40" src="https://github.com/user-attachments/assets/5be3e0b9-04a6-40a8-98d9-d2eef063a9bd">

```php
 * @Nelmio\Operation(
 *     @OA\Parameter(ref="#/components/parameters/limit"),
 *      ...
 *
 * @FOS\RestBundle\Controller\Annotations\QueryParam(name="limit", requirements="[1-9]\d*", description="Limit", default="20", strict=true) 
```

```yaml
# config/nelmio_api_doc.yaml
nelmio_api_doc:
    documentation:
        components:
            parameters:
                limit:
                    name: limit
                    in: query
                    example: 20
                    description: "How many entries per page?"
                    schema:
                        type: integer
```

## working alternative
Compared to this case where there is no duplication:
```
@OA\Parameter(name="limit", in="query", description="How many entries per page?", required=false, @OA\Schema(type="string")),
```
<img width="499" alt="Screenshot 2024-07-15 at 12 40 28" src="https://github.com/user-attachments/assets/72d808f2-38ce-4501-a4c5-9ebf6ecc5191">

### Additional context

Seems similar to the problems described in #1739 and #1407

The error does not happen on parameters of `in: path`
