### ISSUE TITLE
Components `property` is ignored for `@OA\Property`

### ISSUE THREAD

**Issue by jneidel** [nelmio/NelmioApiDocBundle#2315]
### Version

4.28.0

## actual

```yaml
# config/nelmio_api_doc.yaml
nelmio_api_doc:
    documentation:
        components:
            schemas:
                page:
                    property: page      # <-- does not work
                    description: "Current page"
                    type: integer
```

```php
     * @Nelmio\Operation(
     *     @OA\Response(
     *         response=200,
     *         description="OK",
     *         @OA\JsonContent(
     *             @OA\Property(ref="#/components/schemas/page"),
```

This gets you:
<img width="351" alt="Screenshot 2024-07-15 at 17 34 46" src="https://github.com/user-attachments/assets/1314deb2-ed8d-48ff-90da-7f670bb83ab7">

There is `property=""`

## expected

`property="page"`

## workaround

You can get the expected behavior by using 

`@OA\Property(property="page", ref="#/components/schemas/page"),` (specifying property on the Property itself.
<img width="390" alt="Screenshot 2024-07-15 at 17 37 39" src="https://github.com/user-attachments/assets/2a23b02e-95e9-4b03-9262-bf6a69f21fd1">
