### ISSUE TITLE
[Question]: How to insert description for cases of an enum

### ISSUE THREAD

**Issue by mateusfmello** [nelmio/NelmioApiDocBundle#2364]
### Version

v4.32.2

### Question

In an Enum of type int, Swagger is only displaying the values ​​(1,2,3,4...) in the documentation, so it is not possible to know what each case is about.

I would like to be able to add a description for each case

### Additional context

Enum:
```
<?php

namespace App\Enum;

enum TipoAnexoItemPaginaFormEnum: int implements ValidadorEnum {

	use ValidadorEnumTrait;

	case VIDEO_INTERNO = 1;
	case VIDEO_YOUTUBE = 2;
	case VIDEO_VIEMO   = 3;

	case IMAGEM = 4;
	case IFRAME = 5;
	case MAPA   = 6;
}

```

Result:
![image](https://github.com/user-attachments/assets/3c2fe711-21bf-45da-87f8-0923af28c5b5)

I would like a result like this:

```
TipoAnexoItemPaginaFormEnum integer
Enum:

[
	VIDEO_INTERNO = 1,
	VIDEO_YOUTUBE = 2,
	VIDEO_VIEMO = 3,

	IMAGEM = 4,
	IFRAME = 5,
	MAPA = 6,
]
```

**Comment by DjordyKoert** [comment]
This isn't possible.

This bundle uses [swagger-ui](https://github.com/swagger-api/swagger-ui) internally to show the page that you are seeing, I suggest that you open an discussion there 😄

**Comment by keune** [comment]
best method i could find, is to add the schema manually and then referencing that schema from your enum class.

```
#[OA\Schema(ref: '#/components/schemas/TipoAnexoItemPaginaFormEnum')]
enum TipoAnexoItemPaginaFormEnum
```


```
nelmio_api_doc:
    documentation:
        components:
            schemas:
                TipoAnexoItemPaginaFormEnum:
                    type: integer
                    enum:
                        - 1
                        - 2
                        - 3
                    description: |
                        1: Inferno
                        2: Youtube
                        3: Viemo
```


also, i needed to add openapi property attribute wherever i used this enum, otherwise it didn't use the yaml values.

#[OA\Property(type: 'TipoAnexoItemPaginaFormEnum')]
public TipoAnexoItemPaginaFormEnum $myEnum;


not very ideal, since you need to keep two independent places up to date. i hope there'll be a better way in the future.
