### ISSUE TITLE
[Question]: How to assign tags to each area only via yml configuration?

### ISSUE THREAD

**Issue by landsman** [nelmio/NelmioApiDocBundle#2389]
### Version

4.33.4

### Question

I am looking for something like this. I don't want to specify tags, doc in controllers. I want to do it on config level, based on the path prefix.

```yml
nelmio_api_doc:
  documentation:
    info:
      title: "Hello World"
      description: "Test"
      version: "2.0.0"
    tags:
      - name: "Curriculum"
        description: "Module for learning."
      - name: "Warehouse"
        description: "Items and stocktaking."

  areas:
    curriculum:
      path_patterns:
        - ^/v1/curriculum
      documentation:
        tags:
          - { name: "Curriculum" }
    warehouse:
      path_patterns:
        - ^/v1/warehouse
      documentation:
        tags:
          - { name: "Warehouse" }
    default:
      path_patterns:
        - ^/v2/

```
