### ISSUE TITLE
[Question]:  Use a fixed UUID default value instead of randomly generated one in UUIDPropertyDescriber

### ISSUE THREAD

**Issue by TheoD02** [nelmio/NelmioApiDocBundle#2497]
### Version

5.3

### Question

Hello,

Currently, the `UuidPropertyDescriber` generates a random UUID as the default value for UUID properties in the OpenAPI schema. For example:

```yaml
CreateUserCommand:
  id:
    type: string
    format: uuid
    default: 457f9bcd-817b-4fa0-983f-8b615b35c374
```

This causes issues with version control because every time the schema is regenerated, the default UUID changes, resulting in noisy diffs.

**Proposal:**
Instead of generating a random UUID, use a fixed placeholder UUID such as:

```
00000000-0000-0000-0000-000000000000
```

This would stabilize the generated schema files and improve readability and maintainability, without affecting any validation or runtime behavior.

If this sounds good, I’m happy to submit a PR implementing this change.

Thanks !
