### ISSUE TITLE
VirtualProperty not documented

### ISSUE THREAD

**Issue by ogizanagi** [nelmio/NelmioApiDocBundle#269]
When serializing a property as virtual, from a method, no documentation is generated.
As example :

``` php
    /**
     * Question ID
     *
     * @JMSSerializer\Groups({"api_item", "api_list"})
     * @JMSSerializer\VirtualProperty
     * @JMSSerializer\SerializedName("question_id")
     *
     * @return int
     */
    public function serializedQuestionId()
    {
        return $this->question->getId();
    }
```

Property question_id will exist in the returned JSON, but no documentation generated.

**Comment by aistis-** [comment]
Same on Yaml:

```
...
    virtual_properties:
        getUserId:
            serialized_name: user_id
            groups: [api]
            type: integer
```
