### ISSUE TITLE
@output is including form constraints in generated return documention

### ISSUE THREAD

**Issue by dev-ish** [nelmio/NelmioApiDocBundle#349]
I have extended the FOS User entity, and everything works fine with the serializer. And i get the right output from the rest call. 
But in the api documentaion page "/api/doc" i get a return table that includes the form constraints from FOS UserBundle. And if i remove the constraints, in the validation file mentioned below i do get the correct return.

![tictin_api_documentation](https://f.cloud.github.com/assets/1314551/2404972/1d827bf6-aa45-11e3-928d-83d0a3ffabd3.png)

I use the following in my code
```
# Controller
@ApiDoc(
    output={
        "class"   = "Bundle\UserBundle\Entity\User"
    }
)
public function getUserAction(){}
```

```
# Serializer file
Bundle\UserBundle\Entity\User:
    exclusion_policy: ALL
    xml_root_name: user
    properties:
        id:
            since_version: 1.0
            expose: true
            type: string
        firstname:
            since_version: 1.0
            expose: true
            type: string
```

```
# validation file in question.
/vendor/freindsofsymfony/user-bundle/FOS/UserBundle/Resources/config/validation.xml
```
