### ISSUE TITLE
body and accept formats

### ISSUE THREAD

**Issue by bburnichon** [nelmio/NelmioApiDocBundle#544]
When using accept_header to set request format, `Accept` should not be overriden if exists.

I changed the request format part in layout.html.twig to the snippet below:

``` diff
  // set requestFormat
  var requestFormatMethod = '{{ requestFormatMethod }}';
  if (requestFormatMethod == 'format_param') {
    params['_format'] = $('#request_format option:selected').text();
    formData.append('_format',$('#request_format option:selected').text());
  } else if (requestFormatMethod == 'accept_header') {
+   if(!('Accept' in headers)) {
      headers['Accept'] = $('#request_format').val();
+   }
  }
```

What about adding support to more body-types than only form and json.

Something like

``` yml
nelmio_api_doc:
  sandbox:
    body_format:
        formats:
            form: application/x-www-form-urlencoded
            json: application/json
            vndv2: application/vnd.acme;version=2
            vndv3: application/vnd.acme;version=3
        default_format: vndv3
```
