### ISSUE TITLE
Return parameter description

### ISSUE THREAD

**Issue by bkbooth** [nelmio/NelmioApiDocBundle#546]
I can't seem to populate the 'description' field for parameters in the Return section. My return section is set to use an Entity which has both JMS Serializer config and validation rules.

The documentation says:

> For classes parsed with JMS metadata, description will be taken from the properties doc comment, if available.

I've tried putting description in the `{Entity}.php` file:

``` php
class MyEntity
{
    /**
     * My property description
     * @var integer My property description
     */
    private $my_property;
    // ...
}
```

 And the `{Entity}.orm.yml` file:

``` yaml
Foo\MyBundle\Entity\MyEntity:
    type: entity
    fields:
        my_property:
            type: integer
            options:
                comment: My property description
# ...
```

Neither of these approaches have worked, am I missing something or is this feature not working?
