### ISSUE TITLE
JMS Serializer YAML Exclusion policy not correctly parsed

### ISSUE THREAD

**Issue by Soullivaneuh** [nelmio/NelmioApiDocBundle#576]
I have a Plan class with the associated JMS serializer yaml configuration file:

``` yml
AppBundle\Entity\Plan:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            groups: [list, details]
        code:
            expose: true
            groups: [list, details]
        name:
            expose: true
            groups: [list, details]
        shortDescription:
            expose: true
            groups: [details]
        description:
            expose: true
            groups: [details]
        price:
            expose: true
            groups: [details]
```

On a PlanController action, I have this api doc configuration:

``` php
/**
 * @ApiDoc(
 *  description="Returns plan details",
 *  output={
 *      "class"="AppBundle\Entity\Plan",
 *      "groups"={"details"}
 *  }
 * )
 */
```

But the generated doc add extra field like `taxRule` for example:

![nelmio_api_params](https://cloud.githubusercontent.com/assets/1698357/6178186/e75b56a2-b30c-11e4-8311-0cf2d30aef58.png)

Is that a bug? How to fix it?

Thanks.
