### ISSUE TITLE
[Sandbox] HTTPS with host param

### ISSUE THREAD

**Issue by eliecharra** [nelmio/NelmioApiDocBundle#608]
Hi there,
I have problem with the sandbox on a HTTP/HTTPS setup with host params in my routes.
![api](https://cloud.githubusercontent.com/assets/6154987/7376216/8c2ce342-edde-11e4-8fac-195c5a847bc5.png)

I have the following usecase :
I have a single application which manage multiple subdomains like `{api|admin|whatever}.example.com`
I would like all my api methods to be available over HTTP and HTTPS for `api.example.com`

My bundle config :

``` yml
nelmio_api_doc:
    name: "API documentation"
    motd:
        template: 'ApiDocBundle::motd.html.twig'
    sandbox:
        body_format: json
        request_format:
            method: accept_header
            formats:
                json: application/json
                xml: text/xml
            default_format: json
```

My api routing :

``` yml
application_api:
    resource: "@ApiBundle/Resources/config/routing.xml"
    prefix:   /
    host: api.example.com
```

In my routing.xml i import other routes files which contains for example :

``` xml
    <route id="api_get_config" pattern="/config">
        <default key="_controller">ApiBundle:Config:getConfig</default>
        <requirement key="_method">GET</requirement>
    </route>
```

With this setup, the sandbox generate `http://api.example.com/config` endpoints when my browser URL is on 'https://api.example.com/config'

When I fire a REST call from the sandbox chrome gave me :
`Mixed Content: The page at 'https://api.example.com/api/doc/#get--config' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://api.example.com/config'. This request has been blocked; the content must be served over HTTPS.`

I'm I missing something ?

**Comment by phansys** [comment]
Hi @eliecharra.
I have the same issue. I tried with some configs with no luck:

```yaml
# config.yml

nelmio_api_doc:
    sandbox:
        endpoint: https://example.com/api/
```
```php
class MyController
{
    /**
     * @ApiDoc(
     *     https=true
     * )
     *
     * @param Request $request
     */
    public function cgetAction(Request $request)
    {
        // ...
    }
}
```

My locked version:
```
$ composer show -i nelmio/api-doc-bundle
name     : nelmio/api-doc-bundle
descrip. : Generates documentation for your REST API from annotations
keywords : api, doc, documentation, rest
versions : * dev-master, 2.8.x-dev
type     : symfony-bundle
license  : MIT License (MIT) (OSI approved) http://spdx.org/licenses/MIT#licenseText
source   : [git] https://github.com/nelmio/NelmioApiDocBundle.git f7611613af585ac4c6c2d04eb0d4db0f9d01fee0
dist     : [zip] https://api.github.com/repos/nelmio/NelmioApiDocBundle/zipball/f7611613af585ac4c6c2d04eb0d4db0f9d01fee0 f7611613af585ac4c6c2d04eb0d4db0f9d01fee0
names    : nelmio/api-doc-bundle
```

**Comment by phansys** [comment]
After some debug, I found the place where the annotation ```https=true``` is overridden: [PhpDocHandler::handle()](https://github.com/nelmio/NelmioApiDocBundle/blob/master/Extractor/Handler/PhpDocHandler.php#L65).

**Comment by phansys** [comment]
So, after adding ```my_route_name.schemes``` config to my route, it works:

```yaml
# routing.yml

my_route_name:
    type: rest
    resource: MyBundle\Controller\Rest\MyController
    prefix: /api
    defaults: { _format: json }
    schemes: [https]
```
