### ISSUE TITLE
Missing relations on simple formatter

### ISSUE THREAD

**Issue by Soullivaneuh** [nelmio/NelmioApiDocBundle#667]
With the following serializer entity configuration:

``` yaml
AppBundle\Entity\Server:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            groups: [list, details]
        name:
            expose: true
            groups: [list, details]
        status:
            expose: true
            groups: [list, details]
        hostedDomain:
            expose: true
            groups: [list, details]
        alias:
            expose: true
            groups: [details]
        owners:
            expose: true
            groups: [details]
        sshUser:
            expose: true
            groups: [list_admin, details_admin]
        sshPort:
            expose: true
            groups: [list_admin, details_admin]
        mysqlServer:
            expose: true
            groups: [details_admin]
        addedAt:
            expose: true
            groups: [details_admin]
```

And the following controller action:

``` php
/**
 * @ApiDoc(
 *  description="Returns server information",
 *  output={
 *      "class"="AppBundle\Entity\Server",
 *      "groups"={"details"},
 *      "parsers"={
 *          "Nelmio\ApiDocBundle\Parser\JmsMetadataParser"
 *      }
 *  }
 * )
 *
 * @param Server $server
 *
 * @return Response
 */
public function getAction(Server $server)
{
    $view = $this->view($server, 200);
    $context = new SerializationContext();
    $context->setGroups(['details']);
    $view->setSerializationContext($context);

    return $this->handleView($view);
}
```

I got the following **right** rendering on nelmio template:

![nelmio_template](https://cloud.githubusercontent.com/assets/1698357/8499669/6658b278-2195-11e5-880a-afe7abc4763a.png)

But if I try to get it from simple content in order to render a custom view:

``` php
$extractedDoc = $this->get('nelmio_api_doc.extractor.api_doc_extractor')->all();
$simpleContent = $this->get('nelmio_api_doc.formatter.simple_formatter')->format($extractedDoc);
dump($simpleContent);
```

I got this:

```
array:2 [▼
  "/api/servers" => array:2 [▼
    0 => array:9 [▶]
    1 => array:9 [▼
      "method" => "GET"
      "uri" => "/api/servers/{server}.{_format}"
      "description" => "Returns server information"
      "requirements" => array:2 [▶]
      "response" => array:6 [▼
        "id" => array:9 [▶]
        "name" => array:9 [▶]
        "alias" => array:9 [▶]
        "hosted_domain" => array:9 [▶]
        "status" => array:9 [▶]
        "owners" => array:10 [▶]
      ]
      "https" => false
      "authentication" => false
      "authenticationRoles" => []
      "deprecated" => false
    ]
  ]
  "/api/user" => array:1 [▶]
]
```

As you can see, relations are not here.

Is this an issue or am I missing something?
