### ISSUE TITLE
Is it possible to Require a header to be present for all requests and document it? In my case X-Auth-Token

### ISSUE THREAD

**Issue by Ivan0905** [nelmio/NelmioApiDocBundle#673]

**Comment by foaly-nr1** [comment]
```yaml
# app/config/config.yml
nelmio_api_doc:
    sandbox:
        authentication:
            delivery: header
            name:     X-Auth-Token
```

```php
<?php

class YourController
{
    /**
     * @ApiDoc(
     *     authentication=true
     * )
     */
    public function myFunction()
    {
        // ...
    }
}
```
