### ISSUE TITLE
Its difficult (or impossible) to completely disable Nelmio Api Doc on production

### ISSUE THREAD

**Issue by castarco** [nelmio/NelmioApiDocBundle#674]
Hello, there is a related bug  in another project ( https://github.com/Ma27/SenNetwork/issues/153 ) which has been recently resolved (disabling the sandbox in production), but this isn't enough in some cases.

Modifying the AppKernel.php Symfony's file to load the NelmioApiDocBundle only when we are on the dev or test environments doesn't wortk since it crashes<sup>1</sup> when the Symfony's composer hooks try to generate the autoload.php files.

Even more problematic is trying to specify the composer's "nelmio/api-doc-bundle" dependency inside the require-dev block instead of the require block.

In our company we're using Nelmio Api Doc bundle only for developing purposes, we don't want to expose any info in our production environments.

Is there a way to solve this issue? Thanks for your help and your time.

1. Because it tries to parse the nelmio api doc bundle settings file... but Symfony needs a bundle able to "understand" such file. I deeply believe that's a symfony fault rather thant this project's fault... but probably is easier to do the fix here.

**Comment by Laith** [comment]
I have it enabled on dev/testing only and it works fine for me

in AppKernel 
```
if (in_array($this->getEnvironment(), array('dev', 'test'))) {
            $bundles[] = new Nelmio\ApiDocBundle\NelmioApiDocBundle();
}
```
 in `config_dev` 
```
#NelmioApiDocBundle Configuration.
nelmio_api_doc:
    sandbox:
        body_format:
            formats:
                - json
                - form
            default_format: json
        ...
```
