### ISSUE TITLE
Add Support for Parsing FormInterface as input

### ISSUE THREAD

**Issue by ReservedDeveloper** [nelmio/NelmioApiDocBundle#711]
It'd be great to see support for FormInterface as one of the input types.

My use case is that we're using the form factory via service as below:

``` yml
app.form.my_form:
  class: AppBundle\Form\MyForm
  factory: [@form.factory, createNamed]
  [...]
```

Would love to refer to the [form as a service](https://github.com/nelmio/NelmioApiDocBundle/issues/118#issuecomment-85431321). Unfortunately, line [99 of the form parser](https://github.com/nelmio/NelmioApiDocBundle/blob/master/Parser/FormTypeParser.php#L99) kills it. Suspect it would just need to be updated to do a check to see if it is already a FormInterface.

Hopefully will have the opportunity to get a PR in for this in the coming days.
