### ISSUE TITLE
How remove the parameter _format in POST and PUT request

### ISSUE THREAD

**Issue by dbuton** [nelmio/NelmioApiDocBundle#727]
How can I remove the parameter _format sent in POST and PUT request?
There is a special configuration for that?

Thanks

**Comment by stelzek** [comment]
```
  nelmio_api_doc:
      sandbox:
          request_format:
              method: accept_header
```
