### ISSUE TITLE
Swagger Integration not working properly

### ISSUE THREAD

**Issue by MHaendel** [nelmio/NelmioApiDocBundle#745]
Hi,

if swagger tries to access the User Entity, it fails with 

`('Cannot find resource "User"') 
in vendor\nelmio\api-doc-bundle\Nelmio\ApiDocBundle\Controller\ApiDocController.php at line 40` 

Config:

``` yaml
nelmio_api_doc:
    swagger:
        api_base_path:        /api
        swagger_version:      2
        model_naming_strategy: 'last_segment_only'
        api_version:          1
        info:
            title:                Symfony2
            description:          My awesome Symfony2 app!
            TermsOfServiceUrl:    ~
            contact:              ~
            license:              ~
            licenseUrl:           ~
    sandbox:
        authentication:            
            name: access_token 
            delivery: query 
            type: bearer
```

http://project.dev/app_dev.php/api-docs/User
