### ISSUE TITLE
Array to string conversion when I use array parameters in router defaults

### ISSUE THREAD

**Issue by igdr** [nelmio/NelmioApiDocBundle#767]
I have an issue when I try to pass additional parameters to router: http://prntscr.com/9d9qpf

My router configuration is:
```
banner.api.banner:
    path:  /api/banner/banners/{id}
    methods: [GET]
    defaults:
        _controller: AppRestfulBundle:RouterRestful:getResource
        _api:
            manager: banner.manager.banner
    requirements:
        id: \d+
```
