### ISSUE TITLE
Document external dependencies routes

### ISSUE THREAD

**Issue by MatthieuCutin** [nelmio/NelmioApiDocBundle#806]
Hey,

Thank you for this Bundle which i use in every of my projetcs.

I need to document some routes that are actually handled by some of my external bundles (ex: FOSUserBundle or LexikJWTAuthenticationBundle, ...) to show input/output parameters, test them in the sandbox and everything the ApiDoc allows me to do.

In order to do that i created a new service : 

``` php
namespace Acseo\CoreBundle\Service;

use Nelmio\ApiDocBundle\Annotation\ApiDoc;
use Nelmio\ApiDocBundle\Extractor\AnnotationsProviderInterface;
use Symfony\Component\Finder\Finder;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Route;
use Symfony\Component\Yaml\Yaml;

/**
 * Generate annotations for vendor routes to be displayed in Nelmio ApiDoc.
 */
class NelmioApiYmlProvider implements AnnotationsProviderInterface
{
    private $vendorFolder;

    public function __construct($vendorFolder)
    {
        $this->vendorFolder = $vendorFolder;
    }
    /**
     * {@inheritdoc}
     */
    public function getAnnotations()
    {
        $annotations = [];
        $configDirectories = array($this->vendorFolder);

        $finder = new Finder();

        $finder->files()->in($configDirectories);

        if (count($finder) == 0) {
            throw new NotFoundHttpException('No file found for this protocol');
        }

        foreach ($finder as $file_) {
            $data = Yaml::parse(file_get_contents($file_));

            $vendors = array_keys($data);
            foreach ($vendors as $vendor) {
                $apiDoc = new ApiDoc($data[$vendor]);
                $route = new Route(
                    $data[$vendor]['route']['path'],
                    $data[$vendor]['route']['defaults'],
                    $data[$vendor]['route']['requirements'],
                    $data[$vendor]['route']['options'],
                    $data[$vendor]['route']['host'],
                    $data[$vendor]['route']['schemes'],
                    $data[$vendor]['route']['methods'],
                    $data[$vendor]['route']['condition']
                );

                $apiDoc->setRoute($route);
                $apiDoc->setResponse($data[$vendor]['response']);
                $annotations[] = $apiDoc;
            }
        }

        return $annotations;
    }
}
```

and declare it in my service.xml : 

``` xml
                <service id="nelmio_api_doc.yml_provider.acseo_yml_provider" class="%nelmio_api_doc.yml_provider.acseo_yml_provider.class%">
                    <argument>%nelmio_api_doc.vendors.folder%</argument>
                    <tag name="nelmio_api_doc.extractor.annotations_provider" />
                </service>
```

The nelmio_api_doc.vendors.folder parameter is set in the Dependency Injection process that i forked : 
https://github.com/MatthieuCutin/NelmioApiDocBundle/blob/master/DependencyInjection/NelmioApiDocExtension.php
(line 32)
https://github.com/MatthieuCutin/NelmioApiDocBundle/blob/master/DependencyInjection/Configuration.php
(line 165)

But you may use the folder you want.

This allows me to write YAML files that contain any annotations already managed by the ApiDoc : 

``` yml
login_check:
    requirements: []
    views: []
    filters: []
    parameters:
        _password:
            dataType: string
            required: true
            name: _password
            description: Password
            readonly: false
        _username:
            dataType: string
            required: true
            name: _username
            description: Username
            readonly: false
    input: null
    output: null
    link: null
    description: "Get JWT token for logged user"
    section: "Session"
    documentation: null
    resource: null
    method: "POST"
    host: ""
    uri: "/login_check"
    response:
        token:
            dataType: string
            required: true
            description: JWT token
            readonly: true
    route:
        path: /login_check
        defaults:
            _controller: FOS\UserBundle\Controller\SecurityController::checkAction
        requirements: []
        options:
            compiler_class: Symfony\Component\Routing\RouteCompiler
        host: ''
        schemes: []
        methods: [ 'POST' ]
        condition: ''
    https: false
    authentication: false
    authenticationRoles: []
    cache: null
    deprecated: false
    statusCodes: []
    resourceDescription: null
    responseMap: []
    parsedResponseMap: []
    tags: []
```

Now i see my login_check route in my doc and i can use it with the sandbox and i'm happy with that :)

If you think this may be useful for the community i will be glad to make a PR.
Thank you @npotier for your help.

Thank you again for your Bundle !
