### ISSUE TITLE
Validation rules are ignored when a form type is specified as ApiDoc input

### ISSUE THREAD

**Issue by Abam** [nelmio/NelmioApiDocBundle#849]
Given a form type : 

``` php
<?php
namespace AppBundle\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class TestType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('a');
        $builder->add('b');
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => 'AppBundle\Entity\Test',
            'csrf_protection' => false
        ]);
    }
}
```

And validation rules : 

``` yaml
# src/AppBundle/Resources/config/validation.yml
AppBundle\Entity\Test:
    properties:
        a:
            - NotBlank: ~
            - Type: string
        b:
            - NotBlank: ~
            - Type: string
```

When the ApiDoc is specified as follow : 

``` php
<?php
     /**
     * @ApiDoc(
     *    description="My description",
     *    input={"class" = TestType::class, "name"=""}
     * )
```

Then the validation rules are not used in the generated documentation.

Symfony : 3.0.4
ApiDocBundle: 2.12.0
