### ISSUE TITLE
Entity with embbeded collection cannot be used as input in ApiDoc annotation

### ISSUE THREAD

**Issue by Abam** [nelmio/NelmioApiDocBundle#850]
Given an entity: 

``` php
<?php
# src/AppBundle/Entity/Test.php

namespace AppBundle\Entity;

use Symfony\Component\Validator\Constraints as Assert;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity()
 * @ORM\Table(name="test",
 *      uniqueConstraints={@ORM\UniqueConstraint(name="test_name_unique",columns={"name"})}
 * )
 */
class Test
{
    /**
     *
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue
     */
    protected $id;

    /**
     * @ORM\Column(type="string")
     */
    protected $name;

    /**
     * @ORM\OneToMany(targetEntity="Child", mappedBy="myParent")
     * @var Child[]
     */
    protected $children;

    public function getId()
    {
        return $this->id;
    }

    public function getName()
    {
        return $this->name;
    }

    public function setId($id)
    {
        $this->id = $id;
        return $this;
    }

    public function setName($name)
    {
        $this->name = $name;
        return $this;
    }

    public function getChildren()
    {
        return $this->children;
    }

    public function setChildren($children)
    {
        $this->children= $children;
    }
}
```

And validation rules : 

``` yaml
# src/AppBundle/Resources/config/validation.yml
AppBundle\Entity\Test:
    properties:
        a:
            - NotBlank: ~
            - Type: string
        b:
            - NotBlank: ~
            - Type: string
        children:
            - Valid: ~
```

When the ApiDoc is specified as follow : 

``` php
<?php
     /**
     * @ApiDoc(
     *    description="My description",
     *    input={"class" = Test::class}
     * )
```

When trying to access the documentation
Then an exception is thrown with the message `An exception has been thrown during the rendering of a template ("Notice: Array to string conversion") in "NelmioApiDocBundle::method.html.twig" at line 253.`.

Symfony : 3.0.4
ApiDocBundle: 2.12.0
jms/serializer: 1.1.0
jms/serializer-bundle 1.1.0
