### ISSUE TITLE
disable _Locale

### ISSUE THREAD

**Issue by ghost** [nelmio/NelmioApiDocBundle#893]
How can I disable _locale from API DOC?
I have page with 4 languages but I haven't used it inside API.
API DOC generate 4 method for each language like: 

```
PUT /api/dispatch.{_format}
PUT en/api/dispatch.{_format}
PUT ru/api/dispatch.{_format}
```

These are the same methods. How to remove duplicate? (disable locale ony for API)

**Comment by ruscon** [comment]
you need
```
options: { i18n: false }
```

sample
```
user_card_api:
    resource: "@VendorNameBundle/Resources/config/routing/api.yml"
    type: rest
    prefix: /api
    options: { i18n: false }
```
