### ISSUE TITLE
@ApiDoc output param does not work as expected

### ISSUE THREAD

**Issue by exchentrix** [nelmio/NelmioApiDocBundle#905]
Hey,

thank you for this awesome bundle. I noticed some strange behaviour when using the output param in the @ApiDoc Annotation:

```php
/**
 * Returns your user data
 *
 * @ApiDoc(
 *  section="Acl",
 *  description="Returns your user data",
 *  output="BusinessBundle\Model\Acl\Customer\Customer",
 *  statusCodes={
 *      200="Success",
 *      403="Forbidden"
 *  }
 * )
 */
public function getMeAction()
{
	return [
		'user' => $this->get('acl.service')->getUser()
	];
}
```

This action outputs the following:

```json
{
	user: {
		email: "foo@bar.baz",
		name: "Foo Bar Baz",
		locale: "de",
		country: "DE",
		roles: "| ROLE_APP_USER |",
		ip_address: "91.43.133.247",
		newsletter: true,
		last_login: "2016-08-25 21:52:42",
		created_at: "2016-08-25 21:52:42"
	}
}
```

The serialization is done correct. Here is my configuration:

```yml
BusinessBundle\Model\Acl\Customer\om\BaseCustomer:
    exclusion_policy: ALL
    properties:
        email:
            expose: true
        name:
            expose: true
        last_login:
            expose: true
        roles:
            expose: true
        ip_address:
            expose: true
        locale:
            expose: true
        country:
            expose: true
        newsletter:
            expose: true
        created_at:
            expose: true
```

Unfortunately, the api docs just exposes name, email and plain_password (which is excluded). I will attach an screenshot:

![nelmio_api_docs](https://cloud.githubusercontent.com/assets/1130714/17983971/9573d474-6b0f-11e6-903f-4a61d5bc5b3c.jpg)

Do you know, what is wrong here?

Best,
Christian

**Comment by willdurand** [comment]
Mme deo you have serialization groups maybe?

**Comment by exchentrix** [comment]
Hm...no, I dont have serialization groups defined.

**Comment by willdurand** [comment]
Does clearing the cache help? You probably did that already but I cannot find issues with JMS for such a basic example. Except maybe an issue with a version of JMS serializer..

**Comment by exchentrix** [comment]
Yes, I already had cleaned my cache. Just the same result. I'm using 2.13.0 of the bundle.

**Comment by exchentrix** [comment]
Could it has something to do with inheritance or FOSUserBundle? I'm using propel.

The CustomerClass extends an BaseCustomer, which extends an AbstractModel, which extends the BaseObject. The CustomerClass also implements FOS\UserBundle\Model\UserInterface.

**Comment by willdurand** [comment]
I don't think so because the serialization is done properly..

**Comment by exchentrix** [comment]
Hmm....from the Parser\JmsMetaDataParser.php:

```php
// iterate over property metadata
foreach ($meta->propertyMetadata as $item) {

    if (!is_null($item->type)) {
```

Unfortunately, $item->type is null for each $item and so, the parser is not collecting the class properties.

Do you know, what can causes this? I'm on PHP 7 btw.

**Comment by willdurand** [comment]
Maybe a change in the serializer lib then. I thought about this type thing too.

**Comment by exchentrix** [comment]
Strange things are going on...

From the JMS\Serializer\Metadata\Driver\YamlDriver.php

```php
if (isset($pConfig['type'])) {
	$pMetadata->setType((string) $pConfig['type']);
}
```

Seems, that are only setting the type, if you have it configured. I don't have. If I make a test and configure the type, the appropriate property is exposed to the ApiDocs:

```yaml
BusinessBundle\Model\Acl\Customer\om\BaseCustomer:
    exclusion_policy: ALL
    properties:
        email:
            expose: true
        name:
            expose: true
        last_login:
            expose: true
            type: string
        roles:
            expose: true
        ip_address:
            expose: true
        locale:
            expose: true
        country:
            expose: true
        newsletter:
            expose: true
        created_at:
            expose: true
```

In that case "last_login" is visible on the ApiDocs.

Do you know more about that? Is this the default behaviour? I can remember, that I used this whole stuff 2 years ago and at that time, I haven't to configure the type in serializer configuration.

Anyway, for now I will close this issue. Thank you for your help.

Best,
Christian
