### ISSUE TITLE
[3.0] Html output ?

### ISSUE THREAD

**Issue by magnetik** [nelmio/NelmioApiDocBundle#942]
Hey,

I find it disturbingly strange that there are no *easy* way to have a clean/nice HTML output from the swagger.

I've tested ReDoc (javascript), swagger2markup (java), bootprint-openapi (npm).
Since all theses solutions are not in PHP, it's sort of difficult to integrate it directly.

Is it out of the scope of the bundle ?

**Comment by GuilhemN** [comment]
I'd like to integrate [swagger-ui](https://github.com/swagger-api/swagger-ui) directly in the bundle like [Api-platform](https://github.com/api-platform/core) does but I try to focus on the php part for now.
However, PRs are welcome for that :wink:

**Comment by GuilhemN** [comment]
Fixed in #948, you only need to load the route now:
```yml
NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing/swaggerui.xml"
    prefix:   /api/doc
```
