### ISSUE TITLE
Sandbox : How to tell that a route needs authentication

### ISSUE THREAD

**Issue by Yonn-Trimoreau** [nelmio/NelmioApiDocBundle#944]
Hi,

Here is my config.yml :
```
nelmio_api_doc:
    sandbox:
        authentication:
            name: Authorization
            delivery: header
            type: bearer
            custom_endpoint: false
        accept_type: application/json
        body_format:
            formats: [ json ]
            default_format: json
        request_format:
            formats:
                json: application/json
            method: accept_header
            default_format: json
```

Here is an example annotation :
```
    /**
     * Get currently logged in profile
     *
     * @Get("/me")
     *
     * @ApiDoc(
     *   description="Get currently logged in profile",
     *   section="/profile",
     *   resource=true,
     *   headers={
     *     { "name"="Authorization", "description"="Bearer JWT token", "required"=true }
     *   },
     *   statusCodes={
     *     200="Profile found",
     *     401="Invalid JWT authentication"
     *   }
     * )
     *
     * @param UserInterface|User $user
     */
    public function getMyProfileAction(UserInterface $user)
    {
```

I set my api key in NelmioApiDoc's top bar.

Now when I click on "Try It !" for the corresponding route, the Authorization header is not sent :

![api documentation](https://cloud.githubusercontent.com/assets/5746666/21714458/518d4d22-d3ff-11e6-9092-73291ca3e1f8.png)

And my question is : why ?

Thanks in advance
