### ISSUE TITLE
WSSE Token for sandbox

### ISSUE THREAD

**Issue by sergiu-cc** [nelmio/NelmioApiDocBundle#958]
First of all, thank you for this bundle. I'm using it for an API which implements WSSE Token Authorization. It is possible to add/configure the sandbox with the specific header to try the endpoints?

Thank you

**Comment by stingus** [comment]
Yes, configure the bundle:
```
nelmio_api_doc:
  sandbox:
    authentication:
      name: x-wsse
      delivery: header
```
You can than use a WSSE token generator (like https://chrome.google.com/webstore/detail/wsse-generator/piadnaffpgcjalpkfmkpgeamkajfeedc) to get the token properly formatted. Just fill in the token in the top authentication field of Nelmio UI (without the X-WSSE preffix). The downside is that you need to generate a new token for each request, since one WSSE token can only be used once.
