### ISSUE TITLE
error message: the controller value maps a class, but this class was not found.

### ISSUE THREAD

**Issue by coulon-xyz** [nelmio/NelmioApiDocBundle#981]
Hi,

This is a first installation.

I followed the exact steps from symfony's website (https://symfony.com/doc/current/bundles/NelmioApiDocBundle/index.html) and put a generic ApiDoc() on top of one my test function:

```
    /**
     * @ApiDoc(
     *  resource=true,
     *  description="This is a description of your API method",
     *  filters={
     *      {"name"="a-filter", "dataType"="integer"}
     *  }
     * )
     * @Get("test/hello")
     */
    public function getHelloAction(Request $request)
    {
      $formattedResponse = array(
        "hello" => world
      );

```
When I go to the api/doc url (http://localhost:8000/api/doc), I get the following message:  

The _controller value "AppCoreBundle:Profile:myAccount" maps to a "App\CoreBundle\Controller\ProfileController" class, but this class was not found. Create this class or check the spelling of the class and its namespace.

If I go in my CoreBundle routing.yml file, on top of it, I have the definition for the class:
```
my_account:
    path: /mon_compte
    defaults:
        _controller: AppCoreBundle:Profile:myAccount
```

If i remove this entry,  then my top entry in this routing.yml file

```
becomes:google_connect:
    path: /connect-google-api
    defaults:
        _controller: AppCoreBundle:Google:connect
```

And now, if I try to browse the doc again, I've got the following error message:
The _controller value "AppCoreBundle:Google:connect" maps to a "App\CoreBundle\Controller\GoogleController" class, but this class was not found. Create this class or check the spelling of the class and its namespace.

And it goes like that...

It sounds like a namespace issue, but I can't really figure it out.
I already tried to clear the cache, without success.

Anyone has an idea ?

Cheers,
Julien
