### ISSUE TITLE
Custom output from serializier.

### ISSUE THREAD

**Issue by zajca** [nelmio/NelmioApiDocBundle#998]
HI, I'm facing this issue.
I have custom Handler for one entity. And I wan't to show custom output in api doc. So I created own parser, and add value customOutput to output options.

like this:
```
     *     output={
     *          "class"="MyEntity",
     *          "options"={
     *              "customOutput"={
     *                  "id":"integer",
```
I can parse this just fine but after my parser is called also JMS parser which will add all fields. I can add exclude all policy. But still this doesn't looks right. Is there better way how to handle custom output?

**Comment by kirkhelek** [comment]
Hello, if you want to show custom output for an entity you should use serializer groups like in this example:
```
/**
     *
     * @Rest\Get("/foo")
     * @Rest\View(serializerGroups={"api-foo"})
     *
     * @ApiDoc(
     *     resource=true,
     *     description="Foo description",
     *     tags={"Private"},
     *     views={"default", "foo"},
     *     output={
     *          "class"="Acme\YourBundle\Entity\Foo",
     *          "groups"={"api-foo"}
     *     },
     *     statusCodes={
     *          200="I wanna dance in the rain."
     *     }
     * )
     */
    public function getFooAction() { /* do something */   }
```
with your serializer model
`Acme\YourBundle\Resources\config\serializer\Entity.foo.yml`

```
Acme\YoutBundle\Enitty\Foo:
  exclusion_policy: ALL
  properties:
    id:
      expose: true
      groups: ["api-foo", "api-foo1"]
    name:
      expose: true
      groups: ["api-foo"]
    surname:
      expose: true
      groups: ["api-foo"]
```

of course, you will need a serializer like JMS Serializer in your project.

Hope this will help.
